package com.cmcc.medicalcare.model;

import java.util.Date;

public class PatientFastingWeight {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_fasting_weight.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_fasting_weight.weight
     *
     * @mbggenerated
     */
    private String weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_fasting_weight.plan_id
     *
     * @mbggenerated
     */
    private Integer planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_fasting_weight.doctors_id
     *
     * @mbggenerated
     */
    private Integer doctorsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_fasting_weight.doctors_name
     *
     * @mbggenerated
     */
    private String doctorsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_fasting_weight.doctors_phone
     *
     * @mbggenerated
     */
    private String doctorsPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_fasting_weight.patient_id
     *
     * @mbggenerated
     */
    private Integer patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_fasting_weight.patient_name
     *
     * @mbggenerated
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_fasting_weight.patient_phone
     *
     * @mbggenerated
     */
    private String patientPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_fasting_weight.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_fasting_weight.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_fasting_weight.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_fasting_weight.id
     *
     * @return the value of patient_fasting_weight.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_fasting_weight.id
     *
     * @param id the value for patient_fasting_weight.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_fasting_weight.weight
     *
     * @return the value of patient_fasting_weight.weight
     *
     * @mbggenerated
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_fasting_weight.weight
     *
     * @param weight the value for patient_fasting_weight.weight
     *
     * @mbggenerated
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_fasting_weight.plan_id
     *
     * @return the value of patient_fasting_weight.plan_id
     *
     * @mbggenerated
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_fasting_weight.plan_id
     *
     * @param planId the value for patient_fasting_weight.plan_id
     *
     * @mbggenerated
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_fasting_weight.doctors_id
     *
     * @return the value of patient_fasting_weight.doctors_id
     *
     * @mbggenerated
     */
    public Integer getDoctorsId() {
        return doctorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_fasting_weight.doctors_id
     *
     * @param doctorsId the value for patient_fasting_weight.doctors_id
     *
     * @mbggenerated
     */
    public void setDoctorsId(Integer doctorsId) {
        this.doctorsId = doctorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_fasting_weight.doctors_name
     *
     * @return the value of patient_fasting_weight.doctors_name
     *
     * @mbggenerated
     */
    public String getDoctorsName() {
        return doctorsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_fasting_weight.doctors_name
     *
     * @param doctorsName the value for patient_fasting_weight.doctors_name
     *
     * @mbggenerated
     */
    public void setDoctorsName(String doctorsName) {
        this.doctorsName = doctorsName == null ? null : doctorsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_fasting_weight.doctors_phone
     *
     * @return the value of patient_fasting_weight.doctors_phone
     *
     * @mbggenerated
     */
    public String getDoctorsPhone() {
        return doctorsPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_fasting_weight.doctors_phone
     *
     * @param doctorsPhone the value for patient_fasting_weight.doctors_phone
     *
     * @mbggenerated
     */
    public void setDoctorsPhone(String doctorsPhone) {
        this.doctorsPhone = doctorsPhone == null ? null : doctorsPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_fasting_weight.patient_id
     *
     * @return the value of patient_fasting_weight.patient_id
     *
     * @mbggenerated
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_fasting_weight.patient_id
     *
     * @param patientId the value for patient_fasting_weight.patient_id
     *
     * @mbggenerated
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_fasting_weight.patient_name
     *
     * @return the value of patient_fasting_weight.patient_name
     *
     * @mbggenerated
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_fasting_weight.patient_name
     *
     * @param patientName the value for patient_fasting_weight.patient_name
     *
     * @mbggenerated
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_fasting_weight.patient_phone
     *
     * @return the value of patient_fasting_weight.patient_phone
     *
     * @mbggenerated
     */
    public String getPatientPhone() {
        return patientPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_fasting_weight.patient_phone
     *
     * @param patientPhone the value for patient_fasting_weight.patient_phone
     *
     * @mbggenerated
     */
    public void setPatientPhone(String patientPhone) {
        this.patientPhone = patientPhone == null ? null : patientPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_fasting_weight.note
     *
     * @return the value of patient_fasting_weight.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_fasting_weight.note
     *
     * @param note the value for patient_fasting_weight.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_fasting_weight.createtime
     *
     * @return the value of patient_fasting_weight.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_fasting_weight.createtime
     *
     * @param createtime the value for patient_fasting_weight.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_fasting_weight.updatetime
     *
     * @return the value of patient_fasting_weight.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_fasting_weight.updatetime
     *
     * @param updatetime the value for patient_fasting_weight.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}