package com.cmcc.medicalcare.model;

import java.util.Date;

public class PatientInvitation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_invitation.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_invitation.from_patient_id
     *
     * @mbggenerated
     */
    private Integer fromPatientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_invitation.from_patient_name
     *
     * @mbggenerated
     */
    private String fromPatientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_invitation.from_patient_phone
     *
     * @mbggenerated
     */
    private String fromPatientPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_invitation.from_patient_login_id
     *
     * @mbggenerated
     */
    private String fromPatientLoginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_invitation.invite_type
     *
     * @mbggenerated
     */
    private Integer inviteType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_invitation.doctors_id
     *
     * @mbggenerated
     */
    private Integer doctorsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_invitation.doctors_name
     *
     * @mbggenerated
     */
    private String doctorsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_invitation.doctors_phone
     *
     * @mbggenerated
     */
    private String doctorsPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_invitation.doctors_login_id
     *
     * @mbggenerated
     */
    private String doctorsLoginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_invitation.to_patient_id
     *
     * @mbggenerated
     */
    private Integer toPatientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_invitation.to_patient_name
     *
     * @mbggenerated
     */
    private String toPatientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_invitation.to_patient_phone
     *
     * @mbggenerated
     */
    private String toPatientPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_invitation.to_patient_login_id
     *
     * @mbggenerated
     */
    private String toPatientLoginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_invitation.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_invitation.invitetime
     *
     * @mbggenerated
     */
    private Date invitetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_invitation.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_invitation.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_invitation.id
     *
     * @return the value of patient_invitation.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_invitation.id
     *
     * @param id the value for patient_invitation.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_invitation.from_patient_id
     *
     * @return the value of patient_invitation.from_patient_id
     *
     * @mbggenerated
     */
    public Integer getFromPatientId() {
        return fromPatientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_invitation.from_patient_id
     *
     * @param fromPatientId the value for patient_invitation.from_patient_id
     *
     * @mbggenerated
     */
    public void setFromPatientId(Integer fromPatientId) {
        this.fromPatientId = fromPatientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_invitation.from_patient_name
     *
     * @return the value of patient_invitation.from_patient_name
     *
     * @mbggenerated
     */
    public String getFromPatientName() {
        return fromPatientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_invitation.from_patient_name
     *
     * @param fromPatientName the value for patient_invitation.from_patient_name
     *
     * @mbggenerated
     */
    public void setFromPatientName(String fromPatientName) {
        this.fromPatientName = fromPatientName == null ? null : fromPatientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_invitation.from_patient_phone
     *
     * @return the value of patient_invitation.from_patient_phone
     *
     * @mbggenerated
     */
    public String getFromPatientPhone() {
        return fromPatientPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_invitation.from_patient_phone
     *
     * @param fromPatientPhone the value for patient_invitation.from_patient_phone
     *
     * @mbggenerated
     */
    public void setFromPatientPhone(String fromPatientPhone) {
        this.fromPatientPhone = fromPatientPhone == null ? null : fromPatientPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_invitation.from_patient_login_id
     *
     * @return the value of patient_invitation.from_patient_login_id
     *
     * @mbggenerated
     */
    public String getFromPatientLoginId() {
        return fromPatientLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_invitation.from_patient_login_id
     *
     * @param fromPatientLoginId the value for patient_invitation.from_patient_login_id
     *
     * @mbggenerated
     */
    public void setFromPatientLoginId(String fromPatientLoginId) {
        this.fromPatientLoginId = fromPatientLoginId == null ? null : fromPatientLoginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_invitation.invite_type
     *
     * @return the value of patient_invitation.invite_type
     *
     * @mbggenerated
     */
    public Integer getInviteType() {
        return inviteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_invitation.invite_type
     *
     * @param inviteType the value for patient_invitation.invite_type
     *
     * @mbggenerated
     */
    public void setInviteType(Integer inviteType) {
        this.inviteType = inviteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_invitation.doctors_id
     *
     * @return the value of patient_invitation.doctors_id
     *
     * @mbggenerated
     */
    public Integer getDoctorsId() {
        return doctorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_invitation.doctors_id
     *
     * @param doctorsId the value for patient_invitation.doctors_id
     *
     * @mbggenerated
     */
    public void setDoctorsId(Integer doctorsId) {
        this.doctorsId = doctorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_invitation.doctors_name
     *
     * @return the value of patient_invitation.doctors_name
     *
     * @mbggenerated
     */
    public String getDoctorsName() {
        return doctorsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_invitation.doctors_name
     *
     * @param doctorsName the value for patient_invitation.doctors_name
     *
     * @mbggenerated
     */
    public void setDoctorsName(String doctorsName) {
        this.doctorsName = doctorsName == null ? null : doctorsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_invitation.doctors_phone
     *
     * @return the value of patient_invitation.doctors_phone
     *
     * @mbggenerated
     */
    public String getDoctorsPhone() {
        return doctorsPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_invitation.doctors_phone
     *
     * @param doctorsPhone the value for patient_invitation.doctors_phone
     *
     * @mbggenerated
     */
    public void setDoctorsPhone(String doctorsPhone) {
        this.doctorsPhone = doctorsPhone == null ? null : doctorsPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_invitation.doctors_login_id
     *
     * @return the value of patient_invitation.doctors_login_id
     *
     * @mbggenerated
     */
    public String getDoctorsLoginId() {
        return doctorsLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_invitation.doctors_login_id
     *
     * @param doctorsLoginId the value for patient_invitation.doctors_login_id
     *
     * @mbggenerated
     */
    public void setDoctorsLoginId(String doctorsLoginId) {
        this.doctorsLoginId = doctorsLoginId == null ? null : doctorsLoginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_invitation.to_patient_id
     *
     * @return the value of patient_invitation.to_patient_id
     *
     * @mbggenerated
     */
    public Integer getToPatientId() {
        return toPatientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_invitation.to_patient_id
     *
     * @param toPatientId the value for patient_invitation.to_patient_id
     *
     * @mbggenerated
     */
    public void setToPatientId(Integer toPatientId) {
        this.toPatientId = toPatientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_invitation.to_patient_name
     *
     * @return the value of patient_invitation.to_patient_name
     *
     * @mbggenerated
     */
    public String getToPatientName() {
        return toPatientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_invitation.to_patient_name
     *
     * @param toPatientName the value for patient_invitation.to_patient_name
     *
     * @mbggenerated
     */
    public void setToPatientName(String toPatientName) {
        this.toPatientName = toPatientName == null ? null : toPatientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_invitation.to_patient_phone
     *
     * @return the value of patient_invitation.to_patient_phone
     *
     * @mbggenerated
     */
    public String getToPatientPhone() {
        return toPatientPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_invitation.to_patient_phone
     *
     * @param toPatientPhone the value for patient_invitation.to_patient_phone
     *
     * @mbggenerated
     */
    public void setToPatientPhone(String toPatientPhone) {
        this.toPatientPhone = toPatientPhone == null ? null : toPatientPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_invitation.to_patient_login_id
     *
     * @return the value of patient_invitation.to_patient_login_id
     *
     * @mbggenerated
     */
    public String getToPatientLoginId() {
        return toPatientLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_invitation.to_patient_login_id
     *
     * @param toPatientLoginId the value for patient_invitation.to_patient_login_id
     *
     * @mbggenerated
     */
    public void setToPatientLoginId(String toPatientLoginId) {
        this.toPatientLoginId = toPatientLoginId == null ? null : toPatientLoginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_invitation.state
     *
     * @return the value of patient_invitation.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_invitation.state
     *
     * @param state the value for patient_invitation.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_invitation.invitetime
     *
     * @return the value of patient_invitation.invitetime
     *
     * @mbggenerated
     */
    public Date getInvitetime() {
        return invitetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_invitation.invitetime
     *
     * @param invitetime the value for patient_invitation.invitetime
     *
     * @mbggenerated
     */
    public void setInvitetime(Date invitetime) {
        this.invitetime = invitetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_invitation.createtime
     *
     * @return the value of patient_invitation.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_invitation.createtime
     *
     * @param createtime the value for patient_invitation.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_invitation.updatetime
     *
     * @return the value of patient_invitation.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_invitation.updatetime
     *
     * @param updatetime the value for patient_invitation.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}