package com.cmcc.medicalcare.model;

import java.util.Date;

public class PatientBloodPressure {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure.high
     *
     * @mbggenerated
     */
    private String high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure.low
     *
     * @mbggenerated
     */
    private String low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure.pulse
     *
     * @mbggenerated
     */
    private String pulse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure.plan_id
     *
     * @mbggenerated
     */
    private Integer planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure.doctors_id
     *
     * @mbggenerated
     */
    private Integer doctorsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure.doctors_name
     *
     * @mbggenerated
     */
    private String doctorsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure.doctors_phone
     *
     * @mbggenerated
     */
    private String doctorsPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure.patient_id
     *
     * @mbggenerated
     */
    private Integer patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure.patient_name
     *
     * @mbggenerated
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure.patient_phone
     *
     * @mbggenerated
     */
    private String patientPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure.id
     *
     * @return the value of patient_blood_pressure.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure.id
     *
     * @param id the value for patient_blood_pressure.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure.high
     *
     * @return the value of patient_blood_pressure.high
     *
     * @mbggenerated
     */
    public String getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure.high
     *
     * @param high the value for patient_blood_pressure.high
     *
     * @mbggenerated
     */
    public void setHigh(String high) {
        this.high = high == null ? null : high.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure.low
     *
     * @return the value of patient_blood_pressure.low
     *
     * @mbggenerated
     */
    public String getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure.low
     *
     * @param low the value for patient_blood_pressure.low
     *
     * @mbggenerated
     */
    public void setLow(String low) {
        this.low = low == null ? null : low.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure.pulse
     *
     * @return the value of patient_blood_pressure.pulse
     *
     * @mbggenerated
     */
    public String getPulse() {
        return pulse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure.pulse
     *
     * @param pulse the value for patient_blood_pressure.pulse
     *
     * @mbggenerated
     */
    public void setPulse(String pulse) {
        this.pulse = pulse == null ? null : pulse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure.plan_id
     *
     * @return the value of patient_blood_pressure.plan_id
     *
     * @mbggenerated
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure.plan_id
     *
     * @param planId the value for patient_blood_pressure.plan_id
     *
     * @mbggenerated
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure.doctors_id
     *
     * @return the value of patient_blood_pressure.doctors_id
     *
     * @mbggenerated
     */
    public Integer getDoctorsId() {
        return doctorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure.doctors_id
     *
     * @param doctorsId the value for patient_blood_pressure.doctors_id
     *
     * @mbggenerated
     */
    public void setDoctorsId(Integer doctorsId) {
        this.doctorsId = doctorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure.doctors_name
     *
     * @return the value of patient_blood_pressure.doctors_name
     *
     * @mbggenerated
     */
    public String getDoctorsName() {
        return doctorsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure.doctors_name
     *
     * @param doctorsName the value for patient_blood_pressure.doctors_name
     *
     * @mbggenerated
     */
    public void setDoctorsName(String doctorsName) {
        this.doctorsName = doctorsName == null ? null : doctorsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure.doctors_phone
     *
     * @return the value of patient_blood_pressure.doctors_phone
     *
     * @mbggenerated
     */
    public String getDoctorsPhone() {
        return doctorsPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure.doctors_phone
     *
     * @param doctorsPhone the value for patient_blood_pressure.doctors_phone
     *
     * @mbggenerated
     */
    public void setDoctorsPhone(String doctorsPhone) {
        this.doctorsPhone = doctorsPhone == null ? null : doctorsPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure.patient_id
     *
     * @return the value of patient_blood_pressure.patient_id
     *
     * @mbggenerated
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure.patient_id
     *
     * @param patientId the value for patient_blood_pressure.patient_id
     *
     * @mbggenerated
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure.patient_name
     *
     * @return the value of patient_blood_pressure.patient_name
     *
     * @mbggenerated
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure.patient_name
     *
     * @param patientName the value for patient_blood_pressure.patient_name
     *
     * @mbggenerated
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure.patient_phone
     *
     * @return the value of patient_blood_pressure.patient_phone
     *
     * @mbggenerated
     */
    public String getPatientPhone() {
        return patientPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure.patient_phone
     *
     * @param patientPhone the value for patient_blood_pressure.patient_phone
     *
     * @mbggenerated
     */
    public void setPatientPhone(String patientPhone) {
        this.patientPhone = patientPhone == null ? null : patientPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure.note
     *
     * @return the value of patient_blood_pressure.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure.note
     *
     * @param note the value for patient_blood_pressure.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure.createtime
     *
     * @return the value of patient_blood_pressure.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure.createtime
     *
     * @param createtime the value for patient_blood_pressure.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure.updatetime
     *
     * @return the value of patient_blood_pressure.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure.updatetime
     *
     * @param updatetime the value for patient_blood_pressure.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}