
package com.yjktws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "YjktService", targetNamespace = "http://yjktws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface YjktService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bindUserDev", targetNamespace = "http://yjktws.com/", className = "com.yjktws.BindUserDev")
    @ResponseWrapper(localName = "bindUserDevResponse", targetNamespace = "http://yjktws.com/", className = "com.yjktws.BindUserDevResponse")
    public Integer bindUserDev(
        @WebParam(name = "arg0", targetNamespace = "")
        BindDev arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.yjktws.QueryAbpm
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAbpm", targetNamespace = "http://yjktws.com/", className = "com.yjktws.FindAbpm")
    @ResponseWrapper(localName = "findAbpmResponse", targetNamespace = "http://yjktws.com/", className = "com.yjktws.FindAbpmResponse")
    public QueryAbpm findAbpm(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
