package com.cmcc.medicalcare.model;

import java.util.Date;

public class PatientPackage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_package.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_package.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_package.patient_id
     *
     * @mbggenerated
     */
    private Integer patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_package.patient_name
     *
     * @mbggenerated
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_package.patient_phone
     *
     * @mbggenerated
     */
    private String patientPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_package.patient_login_id
     *
     * @mbggenerated
     */
    private String patientLoginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_package.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_package.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_package.doctors_id
     *
     * @mbggenerated
     */
    private Integer doctorsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_package.doctors_name
     *
     * @mbggenerated
     */
    private String doctorsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_package.doctors_phone
     *
     * @mbggenerated
     */
    private String doctorsPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_package.doctors_login_id
     *
     * @mbggenerated
     */
    private String doctorsLoginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_package.online_consultation
     *
     * @mbggenerated
     */
    private String onlineConsultation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_package.remote_diagnosis
     *
     * @mbggenerated
     */
    private String remoteDiagnosis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_package.telephone_consultation
     *
     * @mbggenerated
     */
    private String telephoneConsultation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_package.offline_appointment
     *
     * @mbggenerated
     */
    private String offlineAppointment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_package.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_package.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_package.id
     *
     * @return the value of patient_package.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_package.id
     *
     * @param id the value for patient_package.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_package.name
     *
     * @return the value of patient_package.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_package.name
     *
     * @param name the value for patient_package.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_package.patient_id
     *
     * @return the value of patient_package.patient_id
     *
     * @mbggenerated
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_package.patient_id
     *
     * @param patientId the value for patient_package.patient_id
     *
     * @mbggenerated
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_package.patient_name
     *
     * @return the value of patient_package.patient_name
     *
     * @mbggenerated
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_package.patient_name
     *
     * @param patientName the value for patient_package.patient_name
     *
     * @mbggenerated
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_package.patient_phone
     *
     * @return the value of patient_package.patient_phone
     *
     * @mbggenerated
     */
    public String getPatientPhone() {
        return patientPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_package.patient_phone
     *
     * @param patientPhone the value for patient_package.patient_phone
     *
     * @mbggenerated
     */
    public void setPatientPhone(String patientPhone) {
        this.patientPhone = patientPhone == null ? null : patientPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_package.patient_login_id
     *
     * @return the value of patient_package.patient_login_id
     *
     * @mbggenerated
     */
    public String getPatientLoginId() {
        return patientLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_package.patient_login_id
     *
     * @param patientLoginId the value for patient_package.patient_login_id
     *
     * @mbggenerated
     */
    public void setPatientLoginId(String patientLoginId) {
        this.patientLoginId = patientLoginId == null ? null : patientLoginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_package.start_time
     *
     * @return the value of patient_package.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_package.start_time
     *
     * @param startTime the value for patient_package.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_package.end_time
     *
     * @return the value of patient_package.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_package.end_time
     *
     * @param endTime the value for patient_package.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_package.doctors_id
     *
     * @return the value of patient_package.doctors_id
     *
     * @mbggenerated
     */
    public Integer getDoctorsId() {
        return doctorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_package.doctors_id
     *
     * @param doctorsId the value for patient_package.doctors_id
     *
     * @mbggenerated
     */
    public void setDoctorsId(Integer doctorsId) {
        this.doctorsId = doctorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_package.doctors_name
     *
     * @return the value of patient_package.doctors_name
     *
     * @mbggenerated
     */
    public String getDoctorsName() {
        return doctorsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_package.doctors_name
     *
     * @param doctorsName the value for patient_package.doctors_name
     *
     * @mbggenerated
     */
    public void setDoctorsName(String doctorsName) {
        this.doctorsName = doctorsName == null ? null : doctorsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_package.doctors_phone
     *
     * @return the value of patient_package.doctors_phone
     *
     * @mbggenerated
     */
    public String getDoctorsPhone() {
        return doctorsPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_package.doctors_phone
     *
     * @param doctorsPhone the value for patient_package.doctors_phone
     *
     * @mbggenerated
     */
    public void setDoctorsPhone(String doctorsPhone) {
        this.doctorsPhone = doctorsPhone == null ? null : doctorsPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_package.doctors_login_id
     *
     * @return the value of patient_package.doctors_login_id
     *
     * @mbggenerated
     */
    public String getDoctorsLoginId() {
        return doctorsLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_package.doctors_login_id
     *
     * @param doctorsLoginId the value for patient_package.doctors_login_id
     *
     * @mbggenerated
     */
    public void setDoctorsLoginId(String doctorsLoginId) {
        this.doctorsLoginId = doctorsLoginId == null ? null : doctorsLoginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_package.online_consultation
     *
     * @return the value of patient_package.online_consultation
     *
     * @mbggenerated
     */
    public String getOnlineConsultation() {
        return onlineConsultation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_package.online_consultation
     *
     * @param onlineConsultation the value for patient_package.online_consultation
     *
     * @mbggenerated
     */
    public void setOnlineConsultation(String onlineConsultation) {
        this.onlineConsultation = onlineConsultation == null ? null : onlineConsultation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_package.remote_diagnosis
     *
     * @return the value of patient_package.remote_diagnosis
     *
     * @mbggenerated
     */
    public String getRemoteDiagnosis() {
        return remoteDiagnosis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_package.remote_diagnosis
     *
     * @param remoteDiagnosis the value for patient_package.remote_diagnosis
     *
     * @mbggenerated
     */
    public void setRemoteDiagnosis(String remoteDiagnosis) {
        this.remoteDiagnosis = remoteDiagnosis == null ? null : remoteDiagnosis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_package.telephone_consultation
     *
     * @return the value of patient_package.telephone_consultation
     *
     * @mbggenerated
     */
    public String getTelephoneConsultation() {
        return telephoneConsultation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_package.telephone_consultation
     *
     * @param telephoneConsultation the value for patient_package.telephone_consultation
     *
     * @mbggenerated
     */
    public void setTelephoneConsultation(String telephoneConsultation) {
        this.telephoneConsultation = telephoneConsultation == null ? null : telephoneConsultation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_package.offline_appointment
     *
     * @return the value of patient_package.offline_appointment
     *
     * @mbggenerated
     */
    public String getOfflineAppointment() {
        return offlineAppointment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_package.offline_appointment
     *
     * @param offlineAppointment the value for patient_package.offline_appointment
     *
     * @mbggenerated
     */
    public void setOfflineAppointment(String offlineAppointment) {
        this.offlineAppointment = offlineAppointment == null ? null : offlineAppointment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_package.createtime
     *
     * @return the value of patient_package.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_package.createtime
     *
     * @param createtime the value for patient_package.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_package.updatetime
     *
     * @return the value of patient_package.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_package.updatetime
     *
     * @param updatetime the value for patient_package.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}