package com.cmcc.medicalcare.model;

import java.util.Date;

public class UserFeedback {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feedback.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feedback.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feedback.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feedback.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feedback.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feedback.feedbacktime
     *
     * @mbggenerated
     */
    private Date feedbacktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feedback.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feedback.id
     *
     * @return the value of user_feedback.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feedback.id
     *
     * @param id the value for user_feedback.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feedback.name
     *
     * @return the value of user_feedback.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feedback.name
     *
     * @param name the value for user_feedback.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feedback.content
     *
     * @return the value of user_feedback.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feedback.content
     *
     * @param content the value for user_feedback.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feedback.type
     *
     * @return the value of user_feedback.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feedback.type
     *
     * @param type the value for user_feedback.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feedback.status
     *
     * @return the value of user_feedback.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feedback.status
     *
     * @param status the value for user_feedback.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feedback.feedbacktime
     *
     * @return the value of user_feedback.feedbacktime
     *
     * @mbggenerated
     */
    public Date getFeedbacktime() {
        return feedbacktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feedback.feedbacktime
     *
     * @param feedbacktime the value for user_feedback.feedbacktime
     *
     * @mbggenerated
     */
    public void setFeedbacktime(Date feedbacktime) {
        this.feedbacktime = feedbacktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feedback.createtime
     *
     * @return the value of user_feedback.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feedback.createtime
     *
     * @param createtime the value for user_feedback.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}