package com.cmcc.medicalcare.model;

import java.io.Serializable;
import java.util.Date;

@SuppressWarnings("serial")
public class SensitiveRecordLog implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_record_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_record_log.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_record_log.user_loginid
     *
     * @mbggenerated
     */
    private String userLoginid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_record_log.user_phone
     *
     * @mbggenerated
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_record_log.text
     *
     * @mbggenerated
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_record_log.level
     *
     * @mbggenerated
     */
    private String level;
    
    
    private Integer type;
    
    
    private String toUserName;

 
    private String toUserLoginid;


    private String toUserPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_record_log.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_record_log.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_record_log.id
     *
     * @return the value of sensitive_record_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_record_log.id
     *
     * @param id the value for sensitive_record_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_record_log.user_name
     *
     * @return the value of sensitive_record_log.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_record_log.user_name
     *
     * @param userName the value for sensitive_record_log.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_record_log.user_loginid
     *
     * @return the value of sensitive_record_log.user_loginid
     *
     * @mbggenerated
     */
    public String getUserLoginid() {
        return userLoginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_record_log.user_loginid
     *
     * @param userLoginid the value for sensitive_record_log.user_loginid
     *
     * @mbggenerated
     */
    public void setUserLoginid(String userLoginid) {
        this.userLoginid = userLoginid == null ? null : userLoginid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_record_log.user_phone
     *
     * @return the value of sensitive_record_log.user_phone
     *
     * @mbggenerated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_record_log.user_phone
     *
     * @param userPhone the value for sensitive_record_log.user_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_record_log.text
     *
     * @return the value of sensitive_record_log.text
     *
     * @mbggenerated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_record_log.text
     *
     * @param text the value for sensitive_record_log.text
     *
     * @mbggenerated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_record_log.level
     *
     * @return the value of sensitive_record_log.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_record_log.level
     *
     * @param level the value for sensitive_record_log.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_record_log.createtime
     *
     * @return the value of sensitive_record_log.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_record_log.createtime
     *
     * @param createtime the value for sensitive_record_log.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_record_log.updatetime
     *
     * @return the value of sensitive_record_log.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_record_log.updatetime
     *
     * @param updatetime the value for sensitive_record_log.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

	/**
	 * @return the type
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * @param type the type to set
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * @return the toUserName
	 */
	public String getToUserName() {
		return toUserName;
	}

	/**
	 * @param toUserName the toUserName to set
	 */
	public void setToUserName(String toUserName) {
		this.toUserName = toUserName;
	}

	/**
	 * @return the toUserLoginid
	 */
	public String getToUserLoginid() {
		return toUserLoginid;
	}

	/**
	 * @param toUserLoginid the toUserLoginid to set
	 */
	public void setToUserLoginid(String toUserLoginid) {
		this.toUserLoginid = toUserLoginid;
	}

	/**
	 * @return the toUserPhone
	 */
	public String getToUserPhone() {
		return toUserPhone;
	}

	/**
	 * @param toUserPhone the toUserPhone to set
	 */
	public void setToUserPhone(String toUserPhone) {
		this.toUserPhone = toUserPhone;
	}
    
    
}