package com.cmcc.medicalcare.model;

import java.util.Date;

public class DoctorsFollowupPlanPoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_followup_plan_point.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_followup_plan_point.doctors_followup_plan_id
     *
     * @mbggenerated
     */
    private Integer doctorsFollowupPlanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_followup_plan_point.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_followup_plan_point.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_followup_plan_point.far_from_last _time
     *
     * @mbggenerated
     */
    private Integer farFromLastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_followup_plan_point.plan_time
     *
     * @mbggenerated
     */
    private Date planTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_followup_plan_point.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_followup_plan_point.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_followup_plan_point.doctors_followup_plan_point_template_id
     *
     * @mbggenerated
     */
    private Integer doctorsFollowupPlanPointTemplateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_followup_plan_point.id
     *
     * @return the value of doctors_followup_plan_point.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_followup_plan_point.id
     *
     * @param id the value for doctors_followup_plan_point.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_followup_plan_point.doctors_followup_plan_id
     *
     * @return the value of doctors_followup_plan_point.doctors_followup_plan_id
     *
     * @mbggenerated
     */
    public Integer getDoctorsFollowupPlanId() {
        return doctorsFollowupPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_followup_plan_point.doctors_followup_plan_id
     *
     * @param doctorsFollowupPlanId the value for doctors_followup_plan_point.doctors_followup_plan_id
     *
     * @mbggenerated
     */
    public void setDoctorsFollowupPlanId(Integer doctorsFollowupPlanId) {
        this.doctorsFollowupPlanId = doctorsFollowupPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_followup_plan_point.content
     *
     * @return the value of doctors_followup_plan_point.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_followup_plan_point.content
     *
     * @param content the value for doctors_followup_plan_point.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_followup_plan_point.type
     *
     * @return the value of doctors_followup_plan_point.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_followup_plan_point.type
     *
     * @param type the value for doctors_followup_plan_point.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_followup_plan_point.far_from_last _time
     *
     * @return the value of doctors_followup_plan_point.far_from_last _time
     *
     * @mbggenerated
     */
    public Integer getFarFromLastTime() {
        return farFromLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_followup_plan_point.far_from_last _time
     *
     * @param farFromLastTime the value for doctors_followup_plan_point.far_from_last _time
     *
     * @mbggenerated
     */
    public void setFarFromLastTime(Integer farFromLastTime) {
        this.farFromLastTime = farFromLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_followup_plan_point.plan_time
     *
     * @return the value of doctors_followup_plan_point.plan_time
     *
     * @mbggenerated
     */
    public Date getPlanTime() {
        return planTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_followup_plan_point.plan_time
     *
     * @param planTime the value for doctors_followup_plan_point.plan_time
     *
     * @mbggenerated
     */
    public void setPlanTime(Date planTime) {
        this.planTime = planTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_followup_plan_point.createtime
     *
     * @return the value of doctors_followup_plan_point.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_followup_plan_point.createtime
     *
     * @param createtime the value for doctors_followup_plan_point.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_followup_plan_point.updatetime
     *
     * @return the value of doctors_followup_plan_point.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_followup_plan_point.updatetime
     *
     * @param updatetime the value for doctors_followup_plan_point.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_followup_plan_point.doctors_followup_plan_point_template_id
     *
     * @return the value of doctors_followup_plan_point.doctors_followup_plan_point_template_id
     *
     * @mbggenerated
     */
    public Integer getDoctorsFollowupPlanPointTemplateId() {
        return doctorsFollowupPlanPointTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_followup_plan_point.doctors_followup_plan_point_template_id
     *
     * @param doctorsFollowupPlanPointTemplateId the value for doctors_followup_plan_point.doctors_followup_plan_point_template_id
     *
     * @mbggenerated
     */
    public void setDoctorsFollowupPlanPointTemplateId(Integer doctorsFollowupPlanPointTemplateId) {
        this.doctorsFollowupPlanPointTemplateId = doctorsFollowupPlanPointTemplateId;
    }
}