package com.cmcc.medicalcare.model;

import java.util.Date;

public class SecretaryDoctorsLink {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secretary_doctors_link.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secretary_doctors_link.secretary_id
     *
     * @mbggenerated
     */
    private Integer secretaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secretary_doctors_link.secretary_login_id
     *
     * @mbggenerated
     */
    private String secretaryLoginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secretary_doctors_link.secretary_name
     *
     * @mbggenerated
     */
    private String secretaryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secretary_doctors_link.secretary_phone
     *
     * @mbggenerated
     */
    private String secretaryPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secretary_doctors_link.doctors_id
     *
     * @mbggenerated
     */
    private Integer doctorsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secretary_doctors_link.doctors_name
     *
     * @mbggenerated
     */
    private String doctorsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secretary_doctors_link.doctors_login_id
     *
     * @mbggenerated
     */
    private String doctorsLoginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secretary_doctors_link.doctors_phone
     *
     * @mbggenerated
     */
    private String doctorsPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secretary_doctors_link.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secretary_doctors_link.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secretary_doctors_link.id
     *
     * @return the value of secretary_doctors_link.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secretary_doctors_link.id
     *
     * @param id the value for secretary_doctors_link.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secretary_doctors_link.secretary_id
     *
     * @return the value of secretary_doctors_link.secretary_id
     *
     * @mbggenerated
     */
    public Integer getSecretaryId() {
        return secretaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secretary_doctors_link.secretary_id
     *
     * @param secretaryId the value for secretary_doctors_link.secretary_id
     *
     * @mbggenerated
     */
    public void setSecretaryId(Integer secretaryId) {
        this.secretaryId = secretaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secretary_doctors_link.secretary_login_id
     *
     * @return the value of secretary_doctors_link.secretary_login_id
     *
     * @mbggenerated
     */
    public String getSecretaryLoginId() {
        return secretaryLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secretary_doctors_link.secretary_login_id
     *
     * @param secretaryLoginId the value for secretary_doctors_link.secretary_login_id
     *
     * @mbggenerated
     */
    public void setSecretaryLoginId(String secretaryLoginId) {
        this.secretaryLoginId = secretaryLoginId == null ? null : secretaryLoginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secretary_doctors_link.secretary_name
     *
     * @return the value of secretary_doctors_link.secretary_name
     *
     * @mbggenerated
     */
    public String getSecretaryName() {
        return secretaryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secretary_doctors_link.secretary_name
     *
     * @param secretaryName the value for secretary_doctors_link.secretary_name
     *
     * @mbggenerated
     */
    public void setSecretaryName(String secretaryName) {
        this.secretaryName = secretaryName == null ? null : secretaryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secretary_doctors_link.secretary_phone
     *
     * @return the value of secretary_doctors_link.secretary_phone
     *
     * @mbggenerated
     */
    public String getSecretaryPhone() {
        return secretaryPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secretary_doctors_link.secretary_phone
     *
     * @param secretaryPhone the value for secretary_doctors_link.secretary_phone
     *
     * @mbggenerated
     */
    public void setSecretaryPhone(String secretaryPhone) {
        this.secretaryPhone = secretaryPhone == null ? null : secretaryPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secretary_doctors_link.doctors_id
     *
     * @return the value of secretary_doctors_link.doctors_id
     *
     * @mbggenerated
     */
    public Integer getDoctorsId() {
        return doctorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secretary_doctors_link.doctors_id
     *
     * @param doctorsId the value for secretary_doctors_link.doctors_id
     *
     * @mbggenerated
     */
    public void setDoctorsId(Integer doctorsId) {
        this.doctorsId = doctorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secretary_doctors_link.doctors_name
     *
     * @return the value of secretary_doctors_link.doctors_name
     *
     * @mbggenerated
     */
    public String getDoctorsName() {
        return doctorsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secretary_doctors_link.doctors_name
     *
     * @param doctorsName the value for secretary_doctors_link.doctors_name
     *
     * @mbggenerated
     */
    public void setDoctorsName(String doctorsName) {
        this.doctorsName = doctorsName == null ? null : doctorsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secretary_doctors_link.doctors_login_id
     *
     * @return the value of secretary_doctors_link.doctors_login_id
     *
     * @mbggenerated
     */
    public String getDoctorsLoginId() {
        return doctorsLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secretary_doctors_link.doctors_login_id
     *
     * @param doctorsLoginId the value for secretary_doctors_link.doctors_login_id
     *
     * @mbggenerated
     */
    public void setDoctorsLoginId(String doctorsLoginId) {
        this.doctorsLoginId = doctorsLoginId == null ? null : doctorsLoginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secretary_doctors_link.doctors_phone
     *
     * @return the value of secretary_doctors_link.doctors_phone
     *
     * @mbggenerated
     */
    public String getDoctorsPhone() {
        return doctorsPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secretary_doctors_link.doctors_phone
     *
     * @param doctorsPhone the value for secretary_doctors_link.doctors_phone
     *
     * @mbggenerated
     */
    public void setDoctorsPhone(String doctorsPhone) {
        this.doctorsPhone = doctorsPhone == null ? null : doctorsPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secretary_doctors_link.createtime
     *
     * @return the value of secretary_doctors_link.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secretary_doctors_link.createtime
     *
     * @param createtime the value for secretary_doctors_link.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secretary_doctors_link.updatetime
     *
     * @return the value of secretary_doctors_link.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secretary_doctors_link.updatetime
     *
     * @param updatetime the value for secretary_doctors_link.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}