package com.cmcc.medicalcare.model;

import java.util.Date;

public class ReceiveAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.patient_phone
     *
     * @mbggenerated
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.receive_name
     *
     * @mbggenerated
     */
    private String receiveName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.receive_phone
     *
     * @mbggenerated
     */
    private String receivePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.is_default_address
     *
     * @mbggenerated
     */
    private Integer isDefaultAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.city_name
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.detail_address
     *
     * @mbggenerated
     */
    private String detailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_address.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.id
     *
     * @return the value of receive_address.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.id
     *
     * @param id the value for receive_address.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.patient_phone
     *
     * @return the value of receive_address.patient_phone
     *
     * @mbggenerated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.patient_phone
     *
     * @param patientPhone the value for receive_address.patient_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.receive_name
     *
     * @return the value of receive_address.receive_name
     *
     * @mbggenerated
     */
    public String getReceiveName() {
        return receiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.receive_name
     *
     * @param receiveName the value for receive_address.receive_name
     *
     * @mbggenerated
     */
    public void setReceiveName(String receiveName) {
        this.receiveName = receiveName == null ? null : receiveName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.receive_phone
     *
     * @return the value of receive_address.receive_phone
     *
     * @mbggenerated
     */
    public String getReceivePhone() {
        return receivePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.receive_phone
     *
     * @param receivePhone the value for receive_address.receive_phone
     *
     * @mbggenerated
     */
    public void setReceivePhone(String receivePhone) {
        this.receivePhone = receivePhone == null ? null : receivePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.is_default_address
     *
     * @return the value of receive_address.is_default_address
     *
     * @mbggenerated
     */
    public Integer getIsDefaultAddress() {
        return isDefaultAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.is_default_address
     *
     * @param isDefaultAddress the value for receive_address.is_default_address
     *
     * @mbggenerated
     */
    public void setIsDefaultAddress(Integer isDefaultAddress) {
        this.isDefaultAddress = isDefaultAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.province
     *
     * @return the value of receive_address.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.province
     *
     * @param province the value for receive_address.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.city_name
     *
     * @return the value of receive_address.city_name
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.city_name
     *
     * @param cityName the value for receive_address.city_name
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.area
     *
     * @return the value of receive_address.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.area
     *
     * @param area the value for receive_address.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.detail_address
     *
     * @return the value of receive_address.detail_address
     *
     * @mbggenerated
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.detail_address
     *
     * @param detailAddress the value for receive_address.detail_address
     *
     * @mbggenerated
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress == null ? null : detailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.createtime
     *
     * @return the value of receive_address.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.createtime
     *
     * @param createtime the value for receive_address.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_address.updatetime
     *
     * @return the value of receive_address.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_address.updatetime
     *
     * @param updatetime the value for receive_address.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}