package com.cmcc.medicalcare.model;

import java.util.Date;
import java.util.List;

public class ScienceColumn {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column science_column.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column science_column.column_heading
	 *
	 * @mbggenerated
	 */
	private String columnHeading;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column science_column.on_off
	 *
	 * @mbggenerated
	 */
	private Integer onOff;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column science_column.sequence
	 *
	 * @mbggenerated
	 */
	private Integer sequence;
	
	
	private Integer flag;

	private List<ScienceArticle> scienceArticleList;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column science_column.createtime
	 *
	 * @mbggenerated
	 */
	private Date createtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column science_column.updatetime
	 *
	 * @mbggenerated
	 */
	private Date updatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column science_column.id
	 *
	 * @return the value of science_column.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column science_column.id
	 *
	 * @param id
	 *            the value for science_column.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column science_column.column_heading
	 *
	 * @return the value of science_column.column_heading
	 *
	 * @mbggenerated
	 */
	public String getColumnHeading() {
		return columnHeading;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column science_column.column_heading
	 *
	 * @param columnHeading
	 *            the value for science_column.column_heading
	 *
	 * @mbggenerated
	 */
	public void setColumnHeading(String columnHeading) {
		this.columnHeading = columnHeading == null ? null : columnHeading.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column science_column.on_off
	 *
	 * @return the value of science_column.on_off
	 *
	 * @mbggenerated
	 */
	public Integer getOnOff() {
		return onOff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column science_column.on_off
	 *
	 * @param onOff
	 *            the value for science_column.on_off
	 *
	 * @mbggenerated
	 */
	public void setOnOff(Integer onOff) {
		this.onOff = onOff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column science_column.sequence
	 *
	 * @return the value of science_column.sequence
	 *
	 * @mbggenerated
	 */
	public Integer getSequence() {
		return sequence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column science_column.sequence
	 *
	 * @param sequence
	 *            the value for science_column.sequence
	 *
	 * @mbggenerated
	 */
	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	/**
	 * @return the flag
	 */
	public Integer getFlag() {
		return flag;
	}

	/**
	 * @param flag the flag to set
	 */
	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column science_column.createtime
	 *
	 * @return the value of science_column.createtime
	 *
	 * @mbggenerated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column science_column.createtime
	 *
	 * @param createtime
	 *            the value for science_column.createtime
	 *
	 * @mbggenerated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column science_column.updatetime
	 *
	 * @return the value of science_column.updatetime
	 *
	 * @mbggenerated
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column science_column.updatetime
	 *
	 * @param updatetime
	 *            the value for science_column.updatetime
	 *
	 * @mbggenerated
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * @return the scienceArticleList
	 */
	public List<ScienceArticle> getScienceArticleList() {
		return scienceArticleList;
	}

	/**
	 * @param scienceArticleList
	 *            the scienceArticleList to set
	 */
	public void setScienceArticleList(List<ScienceArticle> scienceArticleList) {
		this.scienceArticleList = scienceArticleList;
	}

}