package com.cmcc.medicalcare.model;

import java.io.Serializable;
import java.util.Date;

@SuppressWarnings("serial")
public class DoctorsTeam implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_team.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_team.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_team.introduction
     *
     * @mbggenerated
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_team.doctors_id
     *
     * @mbggenerated
     */
    private Integer doctorsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_team.doctors_name
     *
     * @mbggenerated
     */
    private String doctorsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_team.doctors_phone
     *
     * @mbggenerated
     */
    private String doctorsPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_team.doctors_login_id
     *
     * @mbggenerated
     */
    private String doctorsLoginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_team.doctors_head_url
     *
     * @mbggenerated
     */
    private String doctorsHeadUrl;

    private String hospitalAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracted_hospitals.hospital_phone
     *
     * @mbggenerated
     */
    private String hospitalPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracted_hospitals.city_name
     *
     * @mbggenerated
     */
    private String province;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracted_hospitals.city_name
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracted_hospitals.area
     *
     * @mbggenerated
     */
    private String area;
    
    private  String hospitalIMG;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_team.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_team.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_team.id
     *
     * @return the value of doctors_team.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_team.id
     *
     * @param id the value for doctors_team.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_team.name
     *
     * @return the value of doctors_team.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_team.name
     *
     * @param name the value for doctors_team.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_team.introduction
     *
     * @return the value of doctors_team.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_team.introduction
     *
     * @param introduction the value for doctors_team.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_team.doctors_id
     *
     * @return the value of doctors_team.doctors_id
     *
     * @mbggenerated
     */
    public Integer getDoctorsId() {
        return doctorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_team.doctors_id
     *
     * @param doctorsId the value for doctors_team.doctors_id
     *
     * @mbggenerated
     */
    public void setDoctorsId(Integer doctorsId) {
        this.doctorsId = doctorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_team.doctors_name
     *
     * @return the value of doctors_team.doctors_name
     *
     * @mbggenerated
     */
    public String getDoctorsName() {
        return doctorsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_team.doctors_name
     *
     * @param doctorsName the value for doctors_team.doctors_name
     *
     * @mbggenerated
     */
    public void setDoctorsName(String doctorsName) {
        this.doctorsName = doctorsName == null ? null : doctorsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_team.doctors_phone
     *
     * @return the value of doctors_team.doctors_phone
     *
     * @mbggenerated
     */
    public String getDoctorsPhone() {
        return doctorsPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_team.doctors_phone
     *
     * @param doctorsPhone the value for doctors_team.doctors_phone
     *
     * @mbggenerated
     */
    public void setDoctorsPhone(String doctorsPhone) {
        this.doctorsPhone = doctorsPhone == null ? null : doctorsPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_team.doctors_login_id
     *
     * @return the value of doctors_team.doctors_login_id
     *
     * @mbggenerated
     */
    public String getDoctorsLoginId() {
        return doctorsLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_team.doctors_login_id
     *
     * @param doctorsLoginId the value for doctors_team.doctors_login_id
     *
     * @mbggenerated
     */
    public void setDoctorsLoginId(String doctorsLoginId) {
        this.doctorsLoginId = doctorsLoginId == null ? null : doctorsLoginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_team.doctors_head_url
     *
     * @return the value of doctors_team.doctors_head_url
     *
     * @mbggenerated
     */
    public String getDoctorsHeadUrl() {
        return doctorsHeadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_team.doctors_head_url
     *
     * @param doctorsHeadUrl the value for doctors_team.doctors_head_url
     *
     * @mbggenerated
     */
    public void setDoctorsHeadUrl(String doctorsHeadUrl) {
        this.doctorsHeadUrl = doctorsHeadUrl == null ? null : doctorsHeadUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_team.createtime
     *
     * @return the value of doctors_team.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_team.createtime
     *
     * @param createtime the value for doctors_team.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_team.updatetime
     *
     * @return the value of doctors_team.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_team.updatetime
     *
     * @param updatetime the value for doctors_team.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

	/**
	 * @return the hospitalAddr
	 */
	public String getHospitalAddr() {
		return hospitalAddr;
	}

	/**
	 * @param hospitalAddr the hospitalAddr to set
	 */
	public void setHospitalAddr(String hospitalAddr) {
		this.hospitalAddr = hospitalAddr;
	}

	/**
	 * @return the hospitalPhone
	 */
	public String getHospitalPhone() {
		return hospitalPhone;
	}

	/**
	 * @param hospitalPhone the hospitalPhone to set
	 */
	public void setHospitalPhone(String hospitalPhone) {
		this.hospitalPhone = hospitalPhone;
	}

	/**
	 * @return the province
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * @param province the province to set
	 */
	public void setProvince(String province) {
		this.province = province;
	}

	/**
	 * @return the cityName
	 */
	public String getCityName() {
		return cityName;
	}

	/**
	 * @param cityName the cityName to set
	 */
	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	/**
	 * @return the area
	 */
	public String getArea() {
		return area;
	}

	/**
	 * @param area the area to set
	 */
	public void setArea(String area) {
		this.area = area;
	}

	/**
	 * @return the hospitalIMG
	 */
	public String getHospitalIMG() {
		return hospitalIMG;
	}

	/**
	 * @param hospitalIMG the hospitalIMG to set
	 */
	public void setHospitalIMG(String hospitalIMG) {
		this.hospitalIMG = hospitalIMG;
	}
}