package com.cmcc.medicalcare.model;

import java.util.Date;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_title
     *
     * @mbggenerated
     */
    private String ordersTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.symptom
     *
     * @mbggenerated
     */
    private String symptom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.requirement
     *
     * @mbggenerated
     */
    private String requirement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.diagnose_time
     *
     * @mbggenerated
     */
    private String diagnoseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.image_url
     *
     * @mbggenerated
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_price
     *
     * @mbggenerated
     */
    private String ordersPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_type
     *
     * @mbggenerated
     */
    private Integer ordersType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_id
     *
     * @mbggenerated
     */
    private Integer prescriptionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_type
     *
     * @mbggenerated
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_pay_state
     *
     * @mbggenerated
     */
    private Integer ordersPayState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_state
     *
     * @mbggenerated
     */
    private Integer ordersState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.patient_login_id
     *
     * @mbggenerated
     */
    private String patientLoginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.patient_name
     *
     * @mbggenerated
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.patient_phone
     *
     * @mbggenerated
     */
    private String patientPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.doctor_login_id
     *
     * @mbggenerated
     */
    private String doctorLoginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.doctor_name
     *
     * @mbggenerated
     */
    private String doctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.doctor_phone
     *
     * @mbggenerated
     */
    private String doctorPhone;
    
    private Long remindTime;

    public Long getRemindTime() {
		return remindTime;
	}

	public void setRemindTime(Long remindTime) {
		this.remindTime = remindTime;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_no
     *
     * @mbggenerated
     */
    private String orderNo;
    private String payOrderNo;

    public String getPayOrderNo() {
		return payOrderNo;
	}

	public void setPayOrderNo(String payOrderNo) {
		this.payOrderNo = payOrderNo;
	}
	
	private Date paytime;

	public Date getPaytime() {
		return paytime;
	}

	public void setPaytime(Date paytime) {
		this.paytime = paytime;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_title
     *
     * @return the value of orders.orders_title
     *
     * @mbggenerated
     */
    public String getOrdersTitle() {
        return ordersTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_title
     *
     * @param ordersTitle the value for orders.orders_title
     *
     * @mbggenerated
     */
    public void setOrdersTitle(String ordersTitle) {
        this.ordersTitle = ordersTitle == null ? null : ordersTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.symptom
     *
     * @return the value of orders.symptom
     *
     * @mbggenerated
     */
    public String getSymptom() {
        return symptom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.symptom
     *
     * @param symptom the value for orders.symptom
     *
     * @mbggenerated
     */
    public void setSymptom(String symptom) {
        this.symptom = symptom == null ? null : symptom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.requirement
     *
     * @return the value of orders.requirement
     *
     * @mbggenerated
     */
    public String getRequirement() {
        return requirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.requirement
     *
     * @param requirement the value for orders.requirement
     *
     * @mbggenerated
     */
    public void setRequirement(String requirement) {
        this.requirement = requirement == null ? null : requirement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.diagnose_time
     *
     * @return the value of orders.diagnose_time
     *
     * @mbggenerated
     */
    public String getDiagnoseTime() {
        return diagnoseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.diagnose_time
     *
     * @param diagnoseTime the value for orders.diagnose_time
     *
     * @mbggenerated
     */
    public void setDiagnoseTime(String diagnoseTime) {
        this.diagnoseTime = diagnoseTime == null ? null : diagnoseTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.image_url
     *
     * @return the value of orders.image_url
     *
     * @mbggenerated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.image_url
     *
     * @param imageUrl the value for orders.image_url
     *
     * @mbggenerated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_price
     *
     * @return the value of orders.orders_price
     *
     * @mbggenerated
     */
    public String getOrdersPrice() {
        return ordersPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_price
     *
     * @param ordersPrice the value for orders.orders_price
     *
     * @mbggenerated
     */
    public void setOrdersPrice(String ordersPrice) {
        this.ordersPrice = ordersPrice == null ? null : ordersPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_type
     *
     * @return the value of orders.orders_type
     *
     * @mbggenerated
     */
    public Integer getOrdersType() {
        return ordersType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_type
     *
     * @param ordersType the value for orders.orders_type
     *
     * @mbggenerated
     */
    public void setOrdersType(Integer ordersType) {
        this.ordersType = ordersType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_id
     *
     * @return the value of orders.order_id
     *
     * @mbggenerated
     */
    public Integer getPrescriptionId() {
        return prescriptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_id
     *
     * @param orderId the value for orders.order_id
     *
     * @mbggenerated
     */
    public void setPrescriptionId(Integer prescriptionId) {
        this.prescriptionId = prescriptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_type
     *
     * @return the value of orders.pay_type
     *
     * @mbggenerated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_type
     *
     * @param payType the value for orders.pay_type
     *
     * @mbggenerated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_pay_state
     *
     * @return the value of orders.orders_pay_state
     *
     * @mbggenerated
     */
    public Integer getOrdersPayState() {
        return ordersPayState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_pay_state
     *
     * @param ordersPayState the value for orders.orders_pay_state
     *
     * @mbggenerated
     */
    public void setOrdersPayState(Integer ordersPayState) {
        this.ordersPayState = ordersPayState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_state
     *
     * @return the value of orders.orders_state
     *
     * @mbggenerated
     */
    public Integer getOrdersState() {
        return ordersState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_state
     *
     * @param ordersState the value for orders.orders_state
     *
     * @mbggenerated
     */
    public void setOrdersState(Integer ordersState) {
        this.ordersState = ordersState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.patient_login_id
     *
     * @return the value of orders.patient_login_id
     *
     * @mbggenerated
     */
    public String getPatientLoginId() {
        return patientLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.patient_login_id
     *
     * @param patientLoginId the value for orders.patient_login_id
     *
     * @mbggenerated
     */
    public void setPatientLoginId(String patientLoginId) {
        this.patientLoginId = patientLoginId == null ? null : patientLoginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.patient_name
     *
     * @return the value of orders.patient_name
     *
     * @mbggenerated
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.patient_name
     *
     * @param patientName the value for orders.patient_name
     *
     * @mbggenerated
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.patient_phone
     *
     * @return the value of orders.patient_phone
     *
     * @mbggenerated
     */
    public String getPatientPhone() {
        return patientPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.patient_phone
     *
     * @param patientPhone the value for orders.patient_phone
     *
     * @mbggenerated
     */
    public void setPatientPhone(String patientPhone) {
        this.patientPhone = patientPhone == null ? null : patientPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.doctor_login_id
     *
     * @return the value of orders.doctor_login_id
     *
     * @mbggenerated
     */
    public String getDoctorLoginId() {
        return doctorLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.doctor_login_id
     *
     * @param doctorLoginId the value for orders.doctor_login_id
     *
     * @mbggenerated
     */
    public void setDoctorLoginId(String doctorLoginId) {
        this.doctorLoginId = doctorLoginId == null ? null : doctorLoginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.doctor_name
     *
     * @return the value of orders.doctor_name
     *
     * @mbggenerated
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.doctor_name
     *
     * @param doctorName the value for orders.doctor_name
     *
     * @mbggenerated
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.doctor_phone
     *
     * @return the value of orders.doctor_phone
     *
     * @mbggenerated
     */
    public String getDoctorPhone() {
        return doctorPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.doctor_phone
     *
     * @param doctorPhone the value for orders.doctor_phone
     *
     * @mbggenerated
     */
    public void setDoctorPhone(String doctorPhone) {
        this.doctorPhone = doctorPhone == null ? null : doctorPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_no
     *
     * @return the value of orders.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_no
     *
     * @param orderNo the value for orders.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.createtime
     *
     * @return the value of orders.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.createtime
     *
     * @param createtime the value for orders.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.updatetime
     *
     * @return the value of orders.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.updatetime
     *
     * @param updatetime the value for orders.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}