package com.cmcc.medicalcare.model;

import java.util.Date;

public class PatientHealthRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.patient_name
     *
     * @mbggenerated
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.patient_phone
     *
     * @mbggenerated
     */
    private String patientPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.patient_login_id
     *
     * @mbggenerated
     */
    private String patientLoginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.height
     *
     * @mbggenerated
     */
    private String height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.weight
     *
     * @mbggenerated
     */
    private String weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.birthday
     *
     * @mbggenerated
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.identification
     *
     * @mbggenerated
     */
    private String identification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.workplace
     *
     * @mbggenerated
     */
    private String workplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.contact_person
     *
     * @mbggenerated
     */
    private String contactPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.contact_person_phone
     *
     * @mbggenerated
     */
    private String contactPersonPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.censustype
     *
     * @mbggenerated
     */
    private String censustype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.ethnic
     *
     * @mbggenerated
     */
    private String ethnic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.bloodtype
     *
     * @mbggenerated
     */
    private String bloodtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.cultural_level
     *
     * @mbggenerated
     */
    private String culturalLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.job
     *
     * @mbggenerated
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.marital_status
     *
     * @mbggenerated
     */
    private String maritalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.payment_method
     *
     * @mbggenerated
     */
    private String paymentMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.radiation_history
     *
     * @mbggenerated
     */
    private String radiationHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.past_history_illness
     *
     * @mbggenerated
     */
    private String pastHistoryIllness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.past_history_surgery
     *
     * @mbggenerated
     */
    private String pastHistorySurgery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.past_history_trauma
     *
     * @mbggenerated
     */
    private String pastHistoryTrauma;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.past_history_transfusion_blood
     *
     * @mbggenerated
     */
    private String pastHistoryTransfusionBlood;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.family_history
     *
     * @mbggenerated
     */
    private String familyHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.genetic_disease
     *
     * @mbggenerated
     */
    private String geneticDisease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.deformity_status
     *
     * @mbggenerated
     */
    private String deformityStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.smoking_history
     *
     * @mbggenerated
     */
    private String smokingHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.drinking_history
     *
     * @mbggenerated
     */
    private String drinkingHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.sleep_state
     *
     * @mbggenerated
     */
    private String sleepState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.stoolurine_is_normal
     *
     * @mbggenerated
     */
    private String stoolurineIsNormal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.drug_history
     *
     * @mbggenerated
     */
    private String drugHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.allergic_history
     *
     * @mbggenerated
     */
    private String allergicHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.diet_history
     *
     * @mbggenerated
     */
    private String dietHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.living_environment
     *
     * @mbggenerated
     */
    private String livingEnvironment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_health_record.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.id
     *
     * @return the value of patient_health_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.id
     *
     * @param id the value for patient_health_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.patient_name
     *
     * @return the value of patient_health_record.patient_name
     *
     * @mbggenerated
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.patient_name
     *
     * @param patientName the value for patient_health_record.patient_name
     *
     * @mbggenerated
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.patient_phone
     *
     * @return the value of patient_health_record.patient_phone
     *
     * @mbggenerated
     */
    public String getPatientPhone() {
        return patientPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.patient_phone
     *
     * @param patientPhone the value for patient_health_record.patient_phone
     *
     * @mbggenerated
     */
    public void setPatientPhone(String patientPhone) {
        this.patientPhone = patientPhone == null ? null : patientPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.patient_login_id
     *
     * @return the value of patient_health_record.patient_login_id
     *
     * @mbggenerated
     */
    public String getPatientLoginId() {
        return patientLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.patient_login_id
     *
     * @param patientLoginId the value for patient_health_record.patient_login_id
     *
     * @mbggenerated
     */
    public void setPatientLoginId(String patientLoginId) {
        this.patientLoginId = patientLoginId == null ? null : patientLoginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.height
     *
     * @return the value of patient_health_record.height
     *
     * @mbggenerated
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.height
     *
     * @param height the value for patient_health_record.height
     *
     * @mbggenerated
     */
    public void setHeight(String height) {
        this.height = height == null ? null : height.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.weight
     *
     * @return the value of patient_health_record.weight
     *
     * @mbggenerated
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.weight
     *
     * @param weight the value for patient_health_record.weight
     *
     * @mbggenerated
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.sex
     *
     * @return the value of patient_health_record.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.sex
     *
     * @param sex the value for patient_health_record.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.birthday
     *
     * @return the value of patient_health_record.birthday
     *
     * @mbggenerated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.birthday
     *
     * @param birthday the value for patient_health_record.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.identification
     *
     * @return the value of patient_health_record.identification
     *
     * @mbggenerated
     */
    public String getIdentification() {
        return identification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.identification
     *
     * @param identification the value for patient_health_record.identification
     *
     * @mbggenerated
     */
    public void setIdentification(String identification) {
        this.identification = identification == null ? null : identification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.workplace
     *
     * @return the value of patient_health_record.workplace
     *
     * @mbggenerated
     */
    public String getWorkplace() {
        return workplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.workplace
     *
     * @param workplace the value for patient_health_record.workplace
     *
     * @mbggenerated
     */
    public void setWorkplace(String workplace) {
        this.workplace = workplace == null ? null : workplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.contact_person
     *
     * @return the value of patient_health_record.contact_person
     *
     * @mbggenerated
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.contact_person
     *
     * @param contactPerson the value for patient_health_record.contact_person
     *
     * @mbggenerated
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson == null ? null : contactPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.contact_person_phone
     *
     * @return the value of patient_health_record.contact_person_phone
     *
     * @mbggenerated
     */
    public String getContactPersonPhone() {
        return contactPersonPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.contact_person_phone
     *
     * @param contactPersonPhone the value for patient_health_record.contact_person_phone
     *
     * @mbggenerated
     */
    public void setContactPersonPhone(String contactPersonPhone) {
        this.contactPersonPhone = contactPersonPhone == null ? null : contactPersonPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.censustype
     *
     * @return the value of patient_health_record.censustype
     *
     * @mbggenerated
     */
    public String getCensustype() {
        return censustype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.censustype
     *
     * @param censustype the value for patient_health_record.censustype
     *
     * @mbggenerated
     */
    public void setCensustype(String censustype) {
        this.censustype = censustype == null ? null : censustype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.ethnic
     *
     * @return the value of patient_health_record.ethnic
     *
     * @mbggenerated
     */
    public String getEthnic() {
        return ethnic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.ethnic
     *
     * @param ethnic the value for patient_health_record.ethnic
     *
     * @mbggenerated
     */
    public void setEthnic(String ethnic) {
        this.ethnic = ethnic == null ? null : ethnic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.bloodtype
     *
     * @return the value of patient_health_record.bloodtype
     *
     * @mbggenerated
     */
    public String getBloodtype() {
        return bloodtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.bloodtype
     *
     * @param bloodtype the value for patient_health_record.bloodtype
     *
     * @mbggenerated
     */
    public void setBloodtype(String bloodtype) {
        this.bloodtype = bloodtype == null ? null : bloodtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.cultural_level
     *
     * @return the value of patient_health_record.cultural_level
     *
     * @mbggenerated
     */
    public String getCulturalLevel() {
        return culturalLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.cultural_level
     *
     * @param culturalLevel the value for patient_health_record.cultural_level
     *
     * @mbggenerated
     */
    public void setCulturalLevel(String culturalLevel) {
        this.culturalLevel = culturalLevel == null ? null : culturalLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.job
     *
     * @return the value of patient_health_record.job
     *
     * @mbggenerated
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.job
     *
     * @param job the value for patient_health_record.job
     *
     * @mbggenerated
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.marital_status
     *
     * @return the value of patient_health_record.marital_status
     *
     * @mbggenerated
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.marital_status
     *
     * @param maritalStatus the value for patient_health_record.marital_status
     *
     * @mbggenerated
     */
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus == null ? null : maritalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.payment_method
     *
     * @return the value of patient_health_record.payment_method
     *
     * @mbggenerated
     */
    public String getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.payment_method
     *
     * @param paymentMethod the value for patient_health_record.payment_method
     *
     * @mbggenerated
     */
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod == null ? null : paymentMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.radiation_history
     *
     * @return the value of patient_health_record.radiation_history
     *
     * @mbggenerated
     */
    public String getRadiationHistory() {
        return radiationHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.radiation_history
     *
     * @param radiationHistory the value for patient_health_record.radiation_history
     *
     * @mbggenerated
     */
    public void setRadiationHistory(String radiationHistory) {
        this.radiationHistory = radiationHistory == null ? null : radiationHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.past_history_illness
     *
     * @return the value of patient_health_record.past_history_illness
     *
     * @mbggenerated
     */
    public String getPastHistoryIllness() {
        return pastHistoryIllness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.past_history_illness
     *
     * @param pastHistoryIllness the value for patient_health_record.past_history_illness
     *
     * @mbggenerated
     */
    public void setPastHistoryIllness(String pastHistoryIllness) {
        this.pastHistoryIllness = pastHistoryIllness == null ? null : pastHistoryIllness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.past_history_surgery
     *
     * @return the value of patient_health_record.past_history_surgery
     *
     * @mbggenerated
     */
    public String getPastHistorySurgery() {
        return pastHistorySurgery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.past_history_surgery
     *
     * @param pastHistorySurgery the value for patient_health_record.past_history_surgery
     *
     * @mbggenerated
     */
    public void setPastHistorySurgery(String pastHistorySurgery) {
        this.pastHistorySurgery = pastHistorySurgery == null ? null : pastHistorySurgery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.past_history_trauma
     *
     * @return the value of patient_health_record.past_history_trauma
     *
     * @mbggenerated
     */
    public String getPastHistoryTrauma() {
        return pastHistoryTrauma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.past_history_trauma
     *
     * @param pastHistoryTrauma the value for patient_health_record.past_history_trauma
     *
     * @mbggenerated
     */
    public void setPastHistoryTrauma(String pastHistoryTrauma) {
        this.pastHistoryTrauma = pastHistoryTrauma == null ? null : pastHistoryTrauma.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.past_history_transfusion_blood
     *
     * @return the value of patient_health_record.past_history_transfusion_blood
     *
     * @mbggenerated
     */
    public String getPastHistoryTransfusionBlood() {
        return pastHistoryTransfusionBlood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.past_history_transfusion_blood
     *
     * @param pastHistoryTransfusionBlood the value for patient_health_record.past_history_transfusion_blood
     *
     * @mbggenerated
     */
    public void setPastHistoryTransfusionBlood(String pastHistoryTransfusionBlood) {
        this.pastHistoryTransfusionBlood = pastHistoryTransfusionBlood == null ? null : pastHistoryTransfusionBlood.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.family_history
     *
     * @return the value of patient_health_record.family_history
     *
     * @mbggenerated
     */
    public String getFamilyHistory() {
        return familyHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.family_history
     *
     * @param familyHistory the value for patient_health_record.family_history
     *
     * @mbggenerated
     */
    public void setFamilyHistory(String familyHistory) {
        this.familyHistory = familyHistory == null ? null : familyHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.genetic_disease
     *
     * @return the value of patient_health_record.genetic_disease
     *
     * @mbggenerated
     */
    public String getGeneticDisease() {
        return geneticDisease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.genetic_disease
     *
     * @param geneticDisease the value for patient_health_record.genetic_disease
     *
     * @mbggenerated
     */
    public void setGeneticDisease(String geneticDisease) {
        this.geneticDisease = geneticDisease == null ? null : geneticDisease.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.deformity_status
     *
     * @return the value of patient_health_record.deformity_status
     *
     * @mbggenerated
     */
    public String getDeformityStatus() {
        return deformityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.deformity_status
     *
     * @param deformityStatus the value for patient_health_record.deformity_status
     *
     * @mbggenerated
     */
    public void setDeformityStatus(String deformityStatus) {
        this.deformityStatus = deformityStatus == null ? null : deformityStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.smoking_history
     *
     * @return the value of patient_health_record.smoking_history
     *
     * @mbggenerated
     */
    public String getSmokingHistory() {
        return smokingHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.smoking_history
     *
     * @param smokingHistory the value for patient_health_record.smoking_history
     *
     * @mbggenerated
     */
    public void setSmokingHistory(String smokingHistory) {
        this.smokingHistory = smokingHistory == null ? null : smokingHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.drinking_history
     *
     * @return the value of patient_health_record.drinking_history
     *
     * @mbggenerated
     */
    public String getDrinkingHistory() {
        return drinkingHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.drinking_history
     *
     * @param drinkingHistory the value for patient_health_record.drinking_history
     *
     * @mbggenerated
     */
    public void setDrinkingHistory(String drinkingHistory) {
        this.drinkingHistory = drinkingHistory == null ? null : drinkingHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.sleep_state
     *
     * @return the value of patient_health_record.sleep_state
     *
     * @mbggenerated
     */
    public String getSleepState() {
        return sleepState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.sleep_state
     *
     * @param sleepState the value for patient_health_record.sleep_state
     *
     * @mbggenerated
     */
    public void setSleepState(String sleepState) {
        this.sleepState = sleepState == null ? null : sleepState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.stoolurine_is_normal
     *
     * @return the value of patient_health_record.stoolurine_is_normal
     *
     * @mbggenerated
     */
    public String getStoolurineIsNormal() {
        return stoolurineIsNormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.stoolurine_is_normal
     *
     * @param stoolurineIsNormal the value for patient_health_record.stoolurine_is_normal
     *
     * @mbggenerated
     */
    public void setStoolurineIsNormal(String stoolurineIsNormal) {
        this.stoolurineIsNormal = stoolurineIsNormal == null ? null : stoolurineIsNormal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.drug_history
     *
     * @return the value of patient_health_record.drug_history
     *
     * @mbggenerated
     */
    public String getDrugHistory() {
        return drugHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.drug_history
     *
     * @param drugHistory the value for patient_health_record.drug_history
     *
     * @mbggenerated
     */
    public void setDrugHistory(String drugHistory) {
        this.drugHistory = drugHistory == null ? null : drugHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.allergic_history
     *
     * @return the value of patient_health_record.allergic_history
     *
     * @mbggenerated
     */
    public String getAllergicHistory() {
        return allergicHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.allergic_history
     *
     * @param allergicHistory the value for patient_health_record.allergic_history
     *
     * @mbggenerated
     */
    public void setAllergicHistory(String allergicHistory) {
        this.allergicHistory = allergicHistory == null ? null : allergicHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.diet_history
     *
     * @return the value of patient_health_record.diet_history
     *
     * @mbggenerated
     */
    public String getDietHistory() {
        return dietHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.diet_history
     *
     * @param dietHistory the value for patient_health_record.diet_history
     *
     * @mbggenerated
     */
    public void setDietHistory(String dietHistory) {
        this.dietHistory = dietHistory == null ? null : dietHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.living_environment
     *
     * @return the value of patient_health_record.living_environment
     *
     * @mbggenerated
     */
    public String getLivingEnvironment() {
        return livingEnvironment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.living_environment
     *
     * @param livingEnvironment the value for patient_health_record.living_environment
     *
     * @mbggenerated
     */
    public void setLivingEnvironment(String livingEnvironment) {
        this.livingEnvironment = livingEnvironment == null ? null : livingEnvironment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.createtime
     *
     * @return the value of patient_health_record.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.createtime
     *
     * @param createtime the value for patient_health_record.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_health_record.updatetime
     *
     * @return the value of patient_health_record.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_health_record.updatetime
     *
     * @param updatetime the value for patient_health_record.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}