package com.cmcc.medicalcare.model;

import java.util.Date;

public class ContractedHospitals {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracted_hospitals.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracted_hospitals.hospital_name
     *
     * @mbggenerated
     */
    private String hospitalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracted_hospitals.hospital_addr
     *
     * @mbggenerated
     */
    private String hospitalAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracted_hospitals.hospital_phone
     *
     * @mbggenerated
     */
    private String hospitalPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracted_hospitals.city_name
     *
     * @mbggenerated
     */
    private String province;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracted_hospitals.city_name
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracted_hospitals.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracted_hospitals.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracted_hospitals.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;
    
    private  String hospitalIMG;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracted_hospitals.id
     *
     * @return the value of contracted_hospitals.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracted_hospitals.id
     *
     * @param id the value for contracted_hospitals.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracted_hospitals.hospital_name
     *
     * @return the value of contracted_hospitals.hospital_name
     *
     * @mbggenerated
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracted_hospitals.hospital_name
     *
     * @param hospitalName the value for contracted_hospitals.hospital_name
     *
     * @mbggenerated
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracted_hospitals.hospital_addr
     *
     * @return the value of contracted_hospitals.hospital_addr
     *
     * @mbggenerated
     */
    public String getHospitalAddr() {
        return hospitalAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracted_hospitals.hospital_addr
     *
     * @param hospitalAddr the value for contracted_hospitals.hospital_addr
     *
     * @mbggenerated
     */
    public void setHospitalAddr(String hospitalAddr) {
        this.hospitalAddr = hospitalAddr == null ? null : hospitalAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracted_hospitals.hospital_phone
     *
     * @return the value of contracted_hospitals.hospital_phone
     *
     * @mbggenerated
     */
    public String getHospitalPhone() {
        return hospitalPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracted_hospitals.hospital_phone
     *
     * @param hospitalPhone the value for contracted_hospitals.hospital_phone
     *
     * @mbggenerated
     */
    public void setHospitalPhone(String hospitalPhone) {
        this.hospitalPhone = hospitalPhone == null ? null : hospitalPhone.trim();
    }

    /**
	 * @return the province
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * @param province the province to set
	 */
	public void setProvince(String province) {
		this.province = province;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracted_hospitals.city_name
     *
     * @return the value of contracted_hospitals.city_name
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracted_hospitals.city_name
     *
     * @param cityName the value for contracted_hospitals.city_name
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracted_hospitals.area
     *
     * @return the value of contracted_hospitals.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracted_hospitals.area
     *
     * @param area the value for contracted_hospitals.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracted_hospitals.createtime
     *
     * @return the value of contracted_hospitals.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracted_hospitals.createtime
     *
     * @param createtime the value for contracted_hospitals.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracted_hospitals.updatetime
     *
     * @return the value of contracted_hospitals.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracted_hospitals.updatetime
     *
     * @param updatetime the value for contracted_hospitals.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

	/**
	 * @return the hospitalIMG
	 */
	public String getHospitalIMG() {
		return hospitalIMG;
	}

	/**
	 * @param hospitalIMG the hospitalIMG to set
	 */
	public void setHospitalIMG(String hospitalIMG) {
		this.hospitalIMG = hospitalIMG;
	}
}