package com.cmcc.medicalcare.model;

import java.util.Date;

public class DoctorsConsultationMessageLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_consultation_message_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_consultation_message_log.chat_group_id
     *
     * @mbggenerated
     */
    private String chatGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_consultation_message_log.chat_group_name
     *
     * @mbggenerated
     */
    private String chatGroupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_consultation_message_log.from_user_login_id
     *
     * @mbggenerated
     */
    private String fromUserLoginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_consultation_message_log.from_user_name
     *
     * @mbggenerated
     */
    private String fromUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_consultation_message_log.from_user_phone
     *
     * @mbggenerated
     */
    private String fromUserPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_consultation_message_log.from_user_type
     *
     * @mbggenerated
     */
    private Integer fromUserType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_consultation_message_log.messageContent
     *
     * @mbggenerated
     */
    private String messagecontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_consultation_message_log.message_type
     *
     * @mbggenerated
     */
    private Integer messageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_consultation_message_log.sendtime
     *
     * @mbggenerated
     */
    private Date sendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_consultation_message_log.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_consultation_message_log.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_consultation_message_log.id
     *
     * @return the value of doctors_consultation_message_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_consultation_message_log.id
     *
     * @param id the value for doctors_consultation_message_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_consultation_message_log.chat_group_id
     *
     * @return the value of doctors_consultation_message_log.chat_group_id
     *
     * @mbggenerated
     */
    public String getChatGroupId() {
        return chatGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_consultation_message_log.chat_group_id
     *
     * @param chatGroupId the value for doctors_consultation_message_log.chat_group_id
     *
     * @mbggenerated
     */
    public void setChatGroupId(String chatGroupId) {
        this.chatGroupId = chatGroupId == null ? null : chatGroupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_consultation_message_log.chat_group_name
     *
     * @return the value of doctors_consultation_message_log.chat_group_name
     *
     * @mbggenerated
     */
    public String getChatGroupName() {
        return chatGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_consultation_message_log.chat_group_name
     *
     * @param chatGroupName the value for doctors_consultation_message_log.chat_group_name
     *
     * @mbggenerated
     */
    public void setChatGroupName(String chatGroupName) {
        this.chatGroupName = chatGroupName == null ? null : chatGroupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_consultation_message_log.from_user_login_id
     *
     * @return the value of doctors_consultation_message_log.from_user_login_id
     *
     * @mbggenerated
     */
    public String getFromUserLoginId() {
        return fromUserLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_consultation_message_log.from_user_login_id
     *
     * @param fromUserLoginId the value for doctors_consultation_message_log.from_user_login_id
     *
     * @mbggenerated
     */
    public void setFromUserLoginId(String fromUserLoginId) {
        this.fromUserLoginId = fromUserLoginId == null ? null : fromUserLoginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_consultation_message_log.from_user_name
     *
     * @return the value of doctors_consultation_message_log.from_user_name
     *
     * @mbggenerated
     */
    public String getFromUserName() {
        return fromUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_consultation_message_log.from_user_name
     *
     * @param fromUserName the value for doctors_consultation_message_log.from_user_name
     *
     * @mbggenerated
     */
    public void setFromUserName(String fromUserName) {
        this.fromUserName = fromUserName == null ? null : fromUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_consultation_message_log.from_user_phone
     *
     * @return the value of doctors_consultation_message_log.from_user_phone
     *
     * @mbggenerated
     */
    public String getFromUserPhone() {
        return fromUserPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_consultation_message_log.from_user_phone
     *
     * @param fromUserPhone the value for doctors_consultation_message_log.from_user_phone
     *
     * @mbggenerated
     */
    public void setFromUserPhone(String fromUserPhone) {
        this.fromUserPhone = fromUserPhone == null ? null : fromUserPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_consultation_message_log.from_user_type
     *
     * @return the value of doctors_consultation_message_log.from_user_type
     *
     * @mbggenerated
     */
    public Integer getFromUserType() {
        return fromUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_consultation_message_log.from_user_type
     *
     * @param fromUserType the value for doctors_consultation_message_log.from_user_type
     *
     * @mbggenerated
     */
    public void setFromUserType(Integer fromUserType) {
        this.fromUserType = fromUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_consultation_message_log.messageContent
     *
     * @return the value of doctors_consultation_message_log.messageContent
     *
     * @mbggenerated
     */
    public String getMessagecontent() {
        return messagecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_consultation_message_log.messageContent
     *
     * @param messagecontent the value for doctors_consultation_message_log.messageContent
     *
     * @mbggenerated
     */
    public void setMessagecontent(String messagecontent) {
        this.messagecontent = messagecontent == null ? null : messagecontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_consultation_message_log.message_type
     *
     * @return the value of doctors_consultation_message_log.message_type
     *
     * @mbggenerated
     */
    public Integer getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_consultation_message_log.message_type
     *
     * @param messageType the value for doctors_consultation_message_log.message_type
     *
     * @mbggenerated
     */
    public void setMessageType(Integer messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_consultation_message_log.sendtime
     *
     * @return the value of doctors_consultation_message_log.sendtime
     *
     * @mbggenerated
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_consultation_message_log.sendtime
     *
     * @param sendtime the value for doctors_consultation_message_log.sendtime
     *
     * @mbggenerated
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_consultation_message_log.createtime
     *
     * @return the value of doctors_consultation_message_log.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_consultation_message_log.createtime
     *
     * @param createtime the value for doctors_consultation_message_log.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_consultation_message_log.updatetime
     *
     * @return the value of doctors_consultation_message_log.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_consultation_message_log.updatetime
     *
     * @param updatetime the value for doctors_consultation_message_log.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}