package com.cmcc.medicalcare.model;

import java.util.Date;

public class HealthReferee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_referee.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_referee.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_referee.user_phone
     *
     * @mbggenerated
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_referee.user_loginid
     *
     * @mbggenerated
     */
    private String userLoginid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_referee.referee_name
     *
     * @mbggenerated
     */
    private String refereeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_referee.referee_phone
     *
     * @mbggenerated
     */
    private String refereePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_referee.referee_loginid
     *
     * @mbggenerated
     */
    private String refereeLoginid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_referee.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_referee.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_referee.id
     *
     * @return the value of health_referee.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_referee.id
     *
     * @param id the value for health_referee.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_referee.user_name
     *
     * @return the value of health_referee.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_referee.user_name
     *
     * @param userName the value for health_referee.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_referee.user_phone
     *
     * @return the value of health_referee.user_phone
     *
     * @mbggenerated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_referee.user_phone
     *
     * @param userPhone the value for health_referee.user_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_referee.user_loginid
     *
     * @return the value of health_referee.user_loginid
     *
     * @mbggenerated
     */
    public String getUserLoginid() {
        return userLoginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_referee.user_loginid
     *
     * @param userLoginid the value for health_referee.user_loginid
     *
     * @mbggenerated
     */
    public void setUserLoginid(String userLoginid) {
        this.userLoginid = userLoginid == null ? null : userLoginid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_referee.referee_name
     *
     * @return the value of health_referee.referee_name
     *
     * @mbggenerated
     */
    public String getRefereeName() {
        return refereeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_referee.referee_name
     *
     * @param refereeName the value for health_referee.referee_name
     *
     * @mbggenerated
     */
    public void setRefereeName(String refereeName) {
        this.refereeName = refereeName == null ? null : refereeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_referee.referee_phone
     *
     * @return the value of health_referee.referee_phone
     *
     * @mbggenerated
     */
    public String getRefereePhone() {
        return refereePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_referee.referee_phone
     *
     * @param refereePhone the value for health_referee.referee_phone
     *
     * @mbggenerated
     */
    public void setRefereePhone(String refereePhone) {
        this.refereePhone = refereePhone == null ? null : refereePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_referee.referee_loginid
     *
     * @return the value of health_referee.referee_loginid
     *
     * @mbggenerated
     */
    public String getRefereeLoginid() {
        return refereeLoginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_referee.referee_loginid
     *
     * @param refereeLoginid the value for health_referee.referee_loginid
     *
     * @mbggenerated
     */
    public void setRefereeLoginid(String refereeLoginid) {
        this.refereeLoginid = refereeLoginid == null ? null : refereeLoginid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_referee.createtime
     *
     * @return the value of health_referee.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_referee.createtime
     *
     * @param createtime the value for health_referee.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_referee.updatetime
     *
     * @return the value of health_referee.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_referee.updatetime
     *
     * @param updatetime the value for health_referee.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}