package com.cmcc.medicalcare.model;

import java.util.Date;

public class HealthCoinsLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_coins_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_coins_log.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_coins_log.user_phone
     *
     * @mbggenerated
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_coins_log.user_loginid
     *
     * @mbggenerated
     */
    private String userLoginid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_coins_log.lcoins
     *
     * @mbggenerated
     */
    private Integer lcoins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_coins_log.mcoins
     *
     * @mbggenerated
     */
    private Integer mcoins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_coins_log.gcoins
     *
     * @mbggenerated
     */
    private Integer gcoins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_coins_log.detail
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_coins_log.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_coins_log.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_coins_log.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_coins_log.id
     *
     * @return the value of health_coins_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_coins_log.id
     *
     * @param id the value for health_coins_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_coins_log.user_name
     *
     * @return the value of health_coins_log.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_coins_log.user_name
     *
     * @param userName the value for health_coins_log.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_coins_log.user_phone
     *
     * @return the value of health_coins_log.user_phone
     *
     * @mbggenerated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_coins_log.user_phone
     *
     * @param userPhone the value for health_coins_log.user_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_coins_log.user_loginid
     *
     * @return the value of health_coins_log.user_loginid
     *
     * @mbggenerated
     */
    public String getUserLoginid() {
        return userLoginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_coins_log.user_loginid
     *
     * @param userLoginid the value for health_coins_log.user_loginid
     *
     * @mbggenerated
     */
    public void setUserLoginid(String userLoginid) {
        this.userLoginid = userLoginid == null ? null : userLoginid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_coins_log.lcoins
     *
     * @return the value of health_coins_log.lcoins
     *
     * @mbggenerated
     */
    public Integer getLcoins() {
        return lcoins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_coins_log.lcoins
     *
     * @param lcoins the value for health_coins_log.lcoins
     *
     * @mbggenerated
     */
    public void setLcoins(Integer lcoins) {
        this.lcoins = lcoins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_coins_log.mcoins
     *
     * @return the value of health_coins_log.mcoins
     *
     * @mbggenerated
     */
    public Integer getMcoins() {
        return mcoins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_coins_log.mcoins
     *
     * @param mcoins the value for health_coins_log.mcoins
     *
     * @mbggenerated
     */
    public void setMcoins(Integer mcoins) {
        this.mcoins = mcoins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_coins_log.gcoins
     *
     * @return the value of health_coins_log.gcoins
     *
     * @mbggenerated
     */
    public Integer getGcoins() {
        return gcoins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_coins_log.gcoins
     *
     * @param gcoins the value for health_coins_log.gcoins
     *
     * @mbggenerated
     */
    public void setGcoins(Integer gcoins) {
        this.gcoins = gcoins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_coins_log.detail
     *
     * @return the value of health_coins_log.detail
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_coins_log.detail
     *
     * @param detail the value for health_coins_log.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_coins_log.type
     *
     * @return the value of health_coins_log.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_coins_log.type
     *
     * @param type the value for health_coins_log.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_coins_log.createtime
     *
     * @return the value of health_coins_log.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_coins_log.createtime
     *
     * @param createtime the value for health_coins_log.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_coins_log.updatetime
     *
     * @return the value of health_coins_log.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_coins_log.updatetime
     *
     * @param updatetime the value for health_coins_log.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}