package com.cmcc.medicalcare.model;

import java.io.Serializable;
import java.util.Date;

@SuppressWarnings("serial")
public class HealthSteps implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_steps.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_steps.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_steps.user_phone
     *
     * @mbggenerated
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_steps.user_loginid
     *
     * @mbggenerated
     */
    private String userLoginid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_steps.steps
     *
     * @mbggenerated
     */
    private Integer steps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_steps.coins
     *
     * @mbggenerated
     */
    private Integer coins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_steps.isget
     *
     * @mbggenerated
     */
    private Integer isget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_steps.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_steps.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_steps.id
     *
     * @return the value of health_steps.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_steps.id
     *
     * @param id the value for health_steps.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_steps.user_name
     *
     * @return the value of health_steps.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_steps.user_name
     *
     * @param userName the value for health_steps.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_steps.user_phone
     *
     * @return the value of health_steps.user_phone
     *
     * @mbggenerated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_steps.user_phone
     *
     * @param userPhone the value for health_steps.user_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_steps.user_loginid
     *
     * @return the value of health_steps.user_loginid
     *
     * @mbggenerated
     */
    public String getUserLoginid() {
        return userLoginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_steps.user_loginid
     *
     * @param userLoginid the value for health_steps.user_loginid
     *
     * @mbggenerated
     */
    public void setUserLoginid(String userLoginid) {
        this.userLoginid = userLoginid == null ? null : userLoginid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_steps.steps
     *
     * @return the value of health_steps.steps
     *
     * @mbggenerated
     */
    public Integer getSteps() {
        return steps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_steps.steps
     *
     * @param steps the value for health_steps.steps
     *
     * @mbggenerated
     */
    public void setSteps(Integer steps) {
        this.steps = steps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_steps.coins
     *
     * @return the value of health_steps.coins
     *
     * @mbggenerated
     */
    public Integer getCoins() {
        return coins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_steps.coins
     *
     * @param coins the value for health_steps.coins
     *
     * @mbggenerated
     */
    public void setCoins(Integer coins) {
        this.coins = coins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_steps.isget
     *
     * @return the value of health_steps.isget
     *
     * @mbggenerated
     */
    public Integer getIsget() {
        return isget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_steps.isget
     *
     * @param isget the value for health_steps.isget
     *
     * @mbggenerated
     */
    public void setIsget(Integer isget) {
        this.isget = isget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_steps.createtime
     *
     * @return the value of health_steps.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_steps.createtime
     *
     * @param createtime the value for health_steps.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_steps.updatetime
     *
     * @return the value of health_steps.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_steps.updatetime
     *
     * @param updatetime the value for health_steps.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}