package com.cmcc.medicalcare.model;

import java.util.Date;

public class PackageVersionDoctor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_version_doctor.h_id
     *
     * @mbggenerated
     */
    private Integer hId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_version_doctor.h_packageVersion
     *
     * @mbggenerated
     */
    private String hPackageversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_version_doctor.h_packageUrl
     *
     * @mbggenerated
     */
    private String hPackageurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_version_doctor.h_status
     *
     * @mbggenerated
     */
    private Integer hStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_version_doctor.h_CREATETIME
     *
     * @mbggenerated
     */
    private Date hCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_version_doctor.h_packageCode
     *
     * @mbggenerated
     */
    private Integer hPackagecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_version_doctor.h_size
     *
     * @mbggenerated
     */
    private Integer hSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_version_doctor.h_serverUrl
     *
     * @mbggenerated
     */
    private String hServerurl;

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_version_doctor.h_id
     *
     * @return the value of package_version_doctor.h_id
     *
     * @mbggenerated
     */
    public Integer gethId() {
        return hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_version_doctor.h_id
     *
     * @param hId the value for package_version_doctor.h_id
     *
     * @mbggenerated
     */
    public void sethId(Integer hId) {
        this.hId = hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_version_doctor.h_packageVersion
     *
     * @return the value of package_version_doctor.h_packageVersion
     *
     * @mbggenerated
     */
    public String gethPackageversion() {
        return hPackageversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_version_doctor.h_packageVersion
     *
     * @param hPackageversion the value for package_version_doctor.h_packageVersion
     *
     * @mbggenerated
     */
    public void sethPackageversion(String hPackageversion) {
        this.hPackageversion = hPackageversion == null ? null : hPackageversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_version_doctor.h_packageUrl
     *
     * @return the value of package_version_doctor.h_packageUrl
     *
     * @mbggenerated
     */
    public String gethPackageurl() {
        return hPackageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_version_doctor.h_packageUrl
     *
     * @param hPackageurl the value for package_version_doctor.h_packageUrl
     *
     * @mbggenerated
     */
    public void sethPackageurl(String hPackageurl) {
        this.hPackageurl = hPackageurl == null ? null : hPackageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_version_doctor.h_status
     *
     * @return the value of package_version_doctor.h_status
     *
     * @mbggenerated
     */
    public Integer gethStatus() {
        return hStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_version_doctor.h_status
     *
     * @param hStatus the value for package_version_doctor.h_status
     *
     * @mbggenerated
     */
    public void sethStatus(Integer hStatus) {
        this.hStatus = hStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_version_doctor.h_CREATETIME
     *
     * @return the value of package_version_doctor.h_CREATETIME
     *
     * @mbggenerated
     */
    public Date gethCreatetime() {
        return hCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_version_doctor.h_CREATETIME
     *
     * @param hCreatetime the value for package_version_doctor.h_CREATETIME
     *
     * @mbggenerated
     */
    public void sethCreatetime(Date hCreatetime) {
        this.hCreatetime = hCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_version_doctor.h_packageCode
     *
     * @return the value of package_version_doctor.h_packageCode
     *
     * @mbggenerated
     */
    public Integer gethPackagecode() {
        return hPackagecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_version_doctor.h_packageCode
     *
     * @param hPackagecode the value for package_version_doctor.h_packageCode
     *
     * @mbggenerated
     */
    public void sethPackagecode(Integer hPackagecode) {
        this.hPackagecode = hPackagecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_version_doctor.h_size
     *
     * @return the value of package_version_doctor.h_size
     *
     * @mbggenerated
     */
    public Integer gethSize() {
        return hSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_version_doctor.h_size
     *
     * @param hSize the value for package_version_doctor.h_size
     *
     * @mbggenerated
     */
    public void sethSize(Integer hSize) {
        this.hSize = hSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_version_doctor.h_serverUrl
     *
     * @return the value of package_version_doctor.h_serverUrl
     *
     * @mbggenerated
     */
    public String gethServerurl() {
        return hServerurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_version_doctor.h_serverUrl
     *
     * @param hServerurl the value for package_version_doctor.h_serverUrl
     *
     * @mbggenerated
     */
    public void sethServerurl(String hServerurl) {
        this.hServerurl = hServerurl == null ? null : hServerurl.trim();
    }
}