package com.cmcc.medicalcare.model;

import java.io.Serializable;
import java.util.Date;

@SuppressWarnings("serial")
public class PatientMedicalRecord implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.patinet_login_id
     *
     * @mbggenerated
     */
    private String patinetLoginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.patinet_name
     *
     * @mbggenerated
     */
    private String patinetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.patient_phone
     *
     * @mbggenerated
     */
    private String patientPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.diagnose_date
     *
     * @mbggenerated
     */
    private Date diagnoseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.diagnose_content
     *
     * @mbggenerated
     */
    private String diagnoseContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.diagnose_result
     *
     * @mbggenerated
     */
    private String diagnoseResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.inspection_report_url
     *
     * @mbggenerated
     */
    private String inspectionReportUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.mechanism
     *
     * @mbggenerated
     */
    private String mechanism;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.source_type
     *
     * @mbggenerated
     */
    private Integer sourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.details
     *
     * @mbggenerated
     */
    private String details;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.doctors_login_id
     *
     * @mbggenerated
     */
    private String doctorsLoginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.doctors_name
     *
     * @mbggenerated
     */
    private String doctorsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.doctors_phone
     *
     * @mbggenerated
     */
    private String doctorsPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.launch_login_id
     *
     * @mbggenerated
     */
    private String launchLoginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.launch_name
     *
     * @mbggenerated
     */
    private String launchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.launch_phone
     *
     * @mbggenerated
     */
    private String launchPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.launch_type
     *
     * @mbggenerated
     */
    private Integer launchType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_medical_record.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;
    
    private String searchStartTime;
    private String searchEndTime;

    public String getSearchStartTime() {
		return searchStartTime;
	}

	public void setSearchStartTime(String searchStartTime) {
		this.searchStartTime = searchStartTime;
	}

	public String getSearchEndTime() {
		return searchEndTime;
	}

	public void setSearchEndTime(String searchEndTime) {
		this.searchEndTime = searchEndTime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.id
     *
     * @return the value of patient_medical_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.id
     *
     * @param id the value for patient_medical_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.patinet_login_id
     *
     * @return the value of patient_medical_record.patinet_login_id
     *
     * @mbggenerated
     */
    public String getPatinetLoginId() {
        return patinetLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.patinet_login_id
     *
     * @param patinetLoginId the value for patient_medical_record.patinet_login_id
     *
     * @mbggenerated
     */
    public void setPatinetLoginId(String patinetLoginId) {
        this.patinetLoginId = patinetLoginId == null ? null : patinetLoginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.patinet_name
     *
     * @return the value of patient_medical_record.patinet_name
     *
     * @mbggenerated
     */
    public String getPatinetName() {
        return patinetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.patinet_name
     *
     * @param patinetName the value for patient_medical_record.patinet_name
     *
     * @mbggenerated
     */
    public void setPatinetName(String patinetName) {
        this.patinetName = patinetName == null ? null : patinetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.patient_phone
     *
     * @return the value of patient_medical_record.patient_phone
     *
     * @mbggenerated
     */
    public String getPatientPhone() {
        return patientPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.patient_phone
     *
     * @param patientPhone the value for patient_medical_record.patient_phone
     *
     * @mbggenerated
     */
    public void setPatientPhone(String patientPhone) {
        this.patientPhone = patientPhone == null ? null : patientPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.diagnose_date
     *
     * @return the value of patient_medical_record.diagnose_date
     *
     * @mbggenerated
     */
    public Date getDiagnoseDate() {
        return diagnoseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.diagnose_date
     *
     * @param diagnoseDate the value for patient_medical_record.diagnose_date
     *
     * @mbggenerated
     */
    public void setDiagnoseDate(Date diagnoseDate) {
        this.diagnoseDate = diagnoseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.diagnose_content
     *
     * @return the value of patient_medical_record.diagnose_content
     *
     * @mbggenerated
     */
    public String getDiagnoseContent() {
        return diagnoseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.diagnose_content
     *
     * @param diagnoseContent the value for patient_medical_record.diagnose_content
     *
     * @mbggenerated
     */
    public void setDiagnoseContent(String diagnoseContent) {
        this.diagnoseContent = diagnoseContent == null ? null : diagnoseContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.diagnose_result
     *
     * @return the value of patient_medical_record.diagnose_result
     *
     * @mbggenerated
     */
    public String getDiagnoseResult() {
        return diagnoseResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.diagnose_result
     *
     * @param diagnoseResult the value for patient_medical_record.diagnose_result
     *
     * @mbggenerated
     */
    public void setDiagnoseResult(String diagnoseResult) {
        this.diagnoseResult = diagnoseResult == null ? null : diagnoseResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.inspection_report_url
     *
     * @return the value of patient_medical_record.inspection_report_url
     *
     * @mbggenerated
     */
    public String getInspectionReportUrl() {
        return inspectionReportUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.inspection_report_url
     *
     * @param inspectionReportUrl the value for patient_medical_record.inspection_report_url
     *
     * @mbggenerated
     */
    public void setInspectionReportUrl(String inspectionReportUrl) {
        this.inspectionReportUrl = inspectionReportUrl == null ? null : inspectionReportUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.mechanism
     *
     * @return the value of patient_medical_record.mechanism
     *
     * @mbggenerated
     */
    public String getMechanism() {
        return mechanism;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.mechanism
     *
     * @param mechanism the value for patient_medical_record.mechanism
     *
     * @mbggenerated
     */
    public void setMechanism(String mechanism) {
        this.mechanism = mechanism == null ? null : mechanism.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.source_type
     *
     * @return the value of patient_medical_record.source_type
     *
     * @mbggenerated
     */
    public Integer getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.source_type
     *
     * @param sourceType the value for patient_medical_record.source_type
     *
     * @mbggenerated
     */
    public void setSourceType(Integer sourceType) {
        this.sourceType = sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.details
     *
     * @return the value of patient_medical_record.details
     *
     * @mbggenerated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.details
     *
     * @param details the value for patient_medical_record.details
     *
     * @mbggenerated
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.doctors_login_id
     *
     * @return the value of patient_medical_record.doctors_login_id
     *
     * @mbggenerated
     */
    public String getDoctorsLoginId() {
        return doctorsLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.doctors_login_id
     *
     * @param doctorsLoginId the value for patient_medical_record.doctors_login_id
     *
     * @mbggenerated
     */
    public void setDoctorsLoginId(String doctorsLoginId) {
        this.doctorsLoginId = doctorsLoginId == null ? null : doctorsLoginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.doctors_name
     *
     * @return the value of patient_medical_record.doctors_name
     *
     * @mbggenerated
     */
    public String getDoctorsName() {
        return doctorsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.doctors_name
     *
     * @param doctorsName the value for patient_medical_record.doctors_name
     *
     * @mbggenerated
     */
    public void setDoctorsName(String doctorsName) {
        this.doctorsName = doctorsName == null ? null : doctorsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.doctors_phone
     *
     * @return the value of patient_medical_record.doctors_phone
     *
     * @mbggenerated
     */
    public String getDoctorsPhone() {
        return doctorsPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.doctors_phone
     *
     * @param doctorsPhone the value for patient_medical_record.doctors_phone
     *
     * @mbggenerated
     */
    public void setDoctorsPhone(String doctorsPhone) {
        this.doctorsPhone = doctorsPhone == null ? null : doctorsPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.state
     *
     * @return the value of patient_medical_record.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.state
     *
     * @param state the value for patient_medical_record.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.note
     *
     * @return the value of patient_medical_record.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.note
     *
     * @param note the value for patient_medical_record.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.launch_login_id
     *
     * @return the value of patient_medical_record.launch_login_id
     *
     * @mbggenerated
     */
    public String getLaunchLoginId() {
        return launchLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.launch_login_id
     *
     * @param launchLoginId the value for patient_medical_record.launch_login_id
     *
     * @mbggenerated
     */
    public void setLaunchLoginId(String launchLoginId) {
        this.launchLoginId = launchLoginId == null ? null : launchLoginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.launch_name
     *
     * @return the value of patient_medical_record.launch_name
     *
     * @mbggenerated
     */
    public String getLaunchName() {
        return launchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.launch_name
     *
     * @param launchName the value for patient_medical_record.launch_name
     *
     * @mbggenerated
     */
    public void setLaunchName(String launchName) {
        this.launchName = launchName == null ? null : launchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.launch_phone
     *
     * @return the value of patient_medical_record.launch_phone
     *
     * @mbggenerated
     */
    public String getLaunchPhone() {
        return launchPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.launch_phone
     *
     * @param launchPhone the value for patient_medical_record.launch_phone
     *
     * @mbggenerated
     */
    public void setLaunchPhone(String launchPhone) {
        this.launchPhone = launchPhone == null ? null : launchPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.launch_type
     *
     * @return the value of patient_medical_record.launch_type
     *
     * @mbggenerated
     */
    public Integer getLaunchType() {
        return launchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.launch_type
     *
     * @param launchType the value for patient_medical_record.launch_type
     *
     * @mbggenerated
     */
    public void setLaunchType(Integer launchType) {
        this.launchType = launchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.createtime
     *
     * @return the value of patient_medical_record.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.createtime
     *
     * @param createtime the value for patient_medical_record.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_medical_record.updatetime
     *
     * @return the value of patient_medical_record.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_medical_record.updatetime
     *
     * @param updatetime the value for patient_medical_record.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}