package com.cmcc.medicalcare.model;

import java.io.Serializable;
import java.util.Date;

@SuppressWarnings("serial")
public class PatientBloodPressureAuto implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure_auto.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure_auto.bp_name
     *
     * @mbggenerated
     */
    private String bpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure_auto.bp_deviceID
     *
     * @mbggenerated
     */
    private String bpDeviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure_auto.bp_measuretime
     *
     * @mbggenerated
     */
    private String bpMeasuretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure_auto.bp_sbp
     *
     * @mbggenerated
     */
    private String bpSbp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure_auto.bp_dbp
     *
     * @mbggenerated
     */
    private String bpDbp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure_auto.bp_pulse
     *
     * @mbggenerated
     */
    private String bpPulse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure_auto.bp_mp
     *
     * @mbggenerated
     */
    private String bpMp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure_auto.bp_status
     *
     * @mbggenerated
     */
    private String bpStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure_auto.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_blood_pressure_auto.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;
    
    private String deviceFrom;

    public String getDeviceFrom() {
		return deviceFrom;
	}
    
    private Integer dataFromType;

	public Integer getDataFromType() {
		return dataFromType;
	}

	public void setDataFromType(Integer dataFromType) {
		this.dataFromType = dataFromType;
	}

	public void setDeviceFrom(String deviceFrom) {
		this.deviceFrom = deviceFrom;
	}
	
	private String patientPhone;
	
	public String getPatientPhone() {
		return patientPhone;
	}

	public void setPatientPhone(String patientPhone) {
		this.patientPhone = patientPhone;
	}

	public Integer getDeviceFromType() {
		return deviceFromType;
	}

	public void setDeviceFromType(Integer deviceFromType) {
		this.deviceFromType = deviceFromType;
	}

	private Integer deviceFromType;

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure_auto.id
     *
     * @return the value of patient_blood_pressure_auto.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure_auto.id
     *
     * @param id the value for patient_blood_pressure_auto.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure_auto.bp_name
     *
     * @return the value of patient_blood_pressure_auto.bp_name
     *
     * @mbggenerated
     */
    public String getBpName() {
        return bpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure_auto.bp_name
     *
     * @param bpName the value for patient_blood_pressure_auto.bp_name
     *
     * @mbggenerated
     */
    public void setBpName(String bpName) {
        this.bpName = bpName == null ? null : bpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure_auto.bp_deviceID
     *
     * @return the value of patient_blood_pressure_auto.bp_deviceID
     *
     * @mbggenerated
     */
    public String getBpDeviceid() {
        return bpDeviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure_auto.bp_deviceID
     *
     * @param bpDeviceid the value for patient_blood_pressure_auto.bp_deviceID
     *
     * @mbggenerated
     */
    public void setBpDeviceid(String bpDeviceid) {
        this.bpDeviceid = bpDeviceid == null ? null : bpDeviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure_auto.bp_measuretime
     *
     * @return the value of patient_blood_pressure_auto.bp_measuretime
     *
     * @mbggenerated
     */
    public String getBpMeasuretime() {
        return bpMeasuretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure_auto.bp_measuretime
     *
     * @param bpMeasuretime the value for patient_blood_pressure_auto.bp_measuretime
     *
     * @mbggenerated
     */
    public void setBpMeasuretime(String bpMeasuretime) {
        this.bpMeasuretime = bpMeasuretime == null ? null : bpMeasuretime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure_auto.bp_sbp
     *
     * @return the value of patient_blood_pressure_auto.bp_sbp
     *
     * @mbggenerated
     */
    public String getBpSbp() {
        return bpSbp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure_auto.bp_sbp
     *
     * @param bpSbp the value for patient_blood_pressure_auto.bp_sbp
     *
     * @mbggenerated
     */
    public void setBpSbp(String bpSbp) {
        this.bpSbp = bpSbp == null ? null : bpSbp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure_auto.bp_dbp
     *
     * @return the value of patient_blood_pressure_auto.bp_dbp
     *
     * @mbggenerated
     */
    public String getBpDbp() {
        return bpDbp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure_auto.bp_dbp
     *
     * @param bpDbp the value for patient_blood_pressure_auto.bp_dbp
     *
     * @mbggenerated
     */
    public void setBpDbp(String bpDbp) {
        this.bpDbp = bpDbp == null ? null : bpDbp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure_auto.bp_pulse
     *
     * @return the value of patient_blood_pressure_auto.bp_pulse
     *
     * @mbggenerated
     */
    public String getBpPulse() {
        return bpPulse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure_auto.bp_pulse
     *
     * @param bpPulse the value for patient_blood_pressure_auto.bp_pulse
     *
     * @mbggenerated
     */
    public void setBpPulse(String bpPulse) {
        this.bpPulse = bpPulse == null ? null : bpPulse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure_auto.bp_mp
     *
     * @return the value of patient_blood_pressure_auto.bp_mp
     *
     * @mbggenerated
     */
    public String getBpMp() {
        return bpMp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure_auto.bp_mp
     *
     * @param bpMp the value for patient_blood_pressure_auto.bp_mp
     *
     * @mbggenerated
     */
    public void setBpMp(String bpMp) {
        this.bpMp = bpMp == null ? null : bpMp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure_auto.bp_status
     *
     * @return the value of patient_blood_pressure_auto.bp_status
     *
     * @mbggenerated
     */
    public String getBpStatus() {
        return bpStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure_auto.bp_status
     *
     * @param bpStatus the value for patient_blood_pressure_auto.bp_status
     *
     * @mbggenerated
     */
    public void setBpStatus(String bpStatus) {
        this.bpStatus = bpStatus == null ? null : bpStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure_auto.createtime
     *
     * @return the value of patient_blood_pressure_auto.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure_auto.createtime
     *
     * @param createtime the value for patient_blood_pressure_auto.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_blood_pressure_auto.updatetime
     *
     * @return the value of patient_blood_pressure_auto.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_blood_pressure_auto.updatetime
     *
     * @param updatetime the value for patient_blood_pressure_auto.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}