package com.cmcc.medicalcare.model;

import java.util.Date;

public class DoctorsTeamUserLink {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_team_user_link.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_team_user_link.team_id
     *
     * @mbggenerated
     */
    private Integer teamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_team_user_link.team_name
     *
     * @mbggenerated
     */
    private String teamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_team_user_link.doctors_id
     *
     * @mbggenerated
     */
    private Integer doctorsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_team_user_link.doctors_name
     *
     * @mbggenerated
     */
    private String doctorsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_team_user_link.doctors_phone
     *
     * @mbggenerated
     */
    private String doctorsPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_team_user_link.doctors_login_id
     *
     * @mbggenerated
     */
    private String doctorsLoginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_team_user_link.isleader
     *
     * @mbggenerated
     */
    private Integer isleader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_team_user_link.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctors_team_user_link.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_team_user_link.id
     *
     * @return the value of doctors_team_user_link.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_team_user_link.id
     *
     * @param id the value for doctors_team_user_link.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_team_user_link.team_id
     *
     * @return the value of doctors_team_user_link.team_id
     *
     * @mbggenerated
     */
    public Integer getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_team_user_link.team_id
     *
     * @param teamId the value for doctors_team_user_link.team_id
     *
     * @mbggenerated
     */
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_team_user_link.team_name
     *
     * @return the value of doctors_team_user_link.team_name
     *
     * @mbggenerated
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_team_user_link.team_name
     *
     * @param teamName the value for doctors_team_user_link.team_name
     *
     * @mbggenerated
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName == null ? null : teamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_team_user_link.doctors_id
     *
     * @return the value of doctors_team_user_link.doctors_id
     *
     * @mbggenerated
     */
    public Integer getDoctorsId() {
        return doctorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_team_user_link.doctors_id
     *
     * @param doctorsId the value for doctors_team_user_link.doctors_id
     *
     * @mbggenerated
     */
    public void setDoctorsId(Integer doctorsId) {
        this.doctorsId = doctorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_team_user_link.doctors_name
     *
     * @return the value of doctors_team_user_link.doctors_name
     *
     * @mbggenerated
     */
    public String getDoctorsName() {
        return doctorsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_team_user_link.doctors_name
     *
     * @param doctorsName the value for doctors_team_user_link.doctors_name
     *
     * @mbggenerated
     */
    public void setDoctorsName(String doctorsName) {
        this.doctorsName = doctorsName == null ? null : doctorsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_team_user_link.doctors_phone
     *
     * @return the value of doctors_team_user_link.doctors_phone
     *
     * @mbggenerated
     */
    public String getDoctorsPhone() {
        return doctorsPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_team_user_link.doctors_phone
     *
     * @param doctorsPhone the value for doctors_team_user_link.doctors_phone
     *
     * @mbggenerated
     */
    public void setDoctorsPhone(String doctorsPhone) {
        this.doctorsPhone = doctorsPhone == null ? null : doctorsPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_team_user_link.doctors_login_id
     *
     * @return the value of doctors_team_user_link.doctors_login_id
     *
     * @mbggenerated
     */
    public String getDoctorsLoginId() {
        return doctorsLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_team_user_link.doctors_login_id
     *
     * @param doctorsLoginId the value for doctors_team_user_link.doctors_login_id
     *
     * @mbggenerated
     */
    public void setDoctorsLoginId(String doctorsLoginId) {
        this.doctorsLoginId = doctorsLoginId == null ? null : doctorsLoginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_team_user_link.isleader
     *
     * @return the value of doctors_team_user_link.isleader
     *
     * @mbggenerated
     */
    public Integer getIsleader() {
        return isleader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_team_user_link.isleader
     *
     * @param isleader the value for doctors_team_user_link.isleader
     *
     * @mbggenerated
     */
    public void setIsleader(Integer isleader) {
        this.isleader = isleader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_team_user_link.createtime
     *
     * @return the value of doctors_team_user_link.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_team_user_link.createtime
     *
     * @param createtime the value for doctors_team_user_link.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctors_team_user_link.updatetime
     *
     * @return the value of doctors_team_user_link.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctors_team_user_link.updatetime
     *
     * @param updatetime the value for doctors_team_user_link.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}